### ISSUE TITLE
Building against nDPI 2.6

### ISSUE THREAD

**Issue by bzed** [pmacct/pmacct#259] opened 2019-01-22 16:31 UTC
hi,

I've tried to build pmacct in debian with libndpi 2.6. The following issues popped up:

- configure fails to detect the headers and libs without settings NDPI_CFLAGS/LIBS
- after setting NDPI_CFLAGS, it still fails as its looking for libndpi/*.h instead of ndpi/*.h or using the CFLAGS.
- fixing the points above it still fails as it tries to detect the static libndpi (which should not be used if there is a dynamic one)
- ndpi 2.6 comes with a different API, building fails completely after fixing (or working around) the issues mentioned above...

The last commits in https://salsa.debian.org/debian/pmacct/commits/ndpi will give you an idea what I've done start building at all...

Debian testing/unstable has an uptodate libndpi-dev package, in case you want to play with it :)

Thanks,

Bernd

**Comment by paololucente** [comment] 2019-01-24 23:00
Hi @bzed , thank you for reporting this. I can confirm all works well compiling against nDPI up to 2.5. I will try to fix soon the building part. But API changes are never a quick win - so i'm marking this as enhancement and will look in that part when possible.

**Comment by paololucente** [comment] 2019-01-25 00:20
Hi @bzed , update: i am leaving things as they are - also on the building side - for the time being since this allows to compile against nDPI 2.2.2 and 2.4-stable GitHub branch (since 2.4 release does not seem to install with a 'make install'). I've hence only updated documentation for now.

**Comment by paololucente** [comment] 2019-04-10 19:01
Hi @bzed , this is done. Both nDPI 2.6 and 2.8 are now supported. 2.4 keeps being supported. 2.2 is not supported anymore and the clutter in the build system related to 2.2 (ie. linking against both shared object and static) is now removed. Going to close this issue, please keep me posted if you manage to give this a try and something does not work out smoothly. Paolo

**Closed by paololucente** 2019-04-10 19:01 UTC
Labels: enhancement
