### ISSUE TITLE
nfacct primitive not working for Layer 4 fields and dataLinkFrameSection

### ISSUE THREAD

**Issue by door7302** [pmacct/pmacct#530] opened 2021-09-14 16:32 UTC
**Description**
Hello,

I'm trying to decode Ethernet/IPv4 packets conveyed into dataLinkFrameSection (IE 315) with a primitive file. It's working fine for layer 3 fields but not for Layer 4 fields. 

For instance my nfacctd conf is the following :

debug: false
debug_internal_msg: false

nfacctd_port: 9997
!plugin_buffer_size: 13107200
!plugin_pipe_size: 1342177280
nfacctd_disable_checks: false
!
plugins: kafka
!
aggregate_primitives: /var/tmp/primitive.lst
aggregate: sampling_rate,ip4_src, ip4_dst, ip4_proto, sp, dp
!

kafka_broker_host: x.x.x.x
kafka_output: json
kafka_topic: imon-dib
kafka_refresh_time: 60
kafka_history: 60s
kafka_history_roundoff: m

and my primitive file is : 

name=ip4_src packet_ptr=l3:0x0800+12 len=4 semantics=ip
name=ip4_dst packet_ptr=l3:0x0800+16 len=4 semantics=ip
name=ip4_proto packet_ptr=l3:0x0800+9 len=1 semantics=u_int

name=sp packet_ptr=l4:17 len=2 semantics=u_int           # Source UDP port
name=dp packet_ptr=l4:17+2 len=2 semantics=u_int      # Destination UDP port

Export is working fine but as you can see my sp and dp fields are always set to 0, other fields are good. 

{"event_type": "purge", "sampling_rate": 1000, "ip4_src": "172.17.0.1", "ip4_dst": "3.0.0.2", "ip4_proto": "17", "sp": "0", "dp": "0", "stamp_inserted": "2021-09-14 16:17:00", "stamp_updated": "2021-09-14 16:18:01", "packets": 420, "bytes": 205800, "writer_id": "default_kafka/13"}

If I change my primitive file like that : 

name=ip4_src packet_ptr=l3:0x0800+12 len=4 semantics=ip
name=ip4_dst packet_ptr=l3:0x0800+16 len=4 semantics=ip
name=ip4_proto packet_ptr=l3:0x0800+9 len=1 semantics=u_int

name=sp packet_ptr=l3:0x0800+20 len=2 semantics=u_int
name=dp packet_ptr=l3:0x0800+22 len=2 semantics=u_int

Now my sp and dp fields are good : 

{"event_type": "purge", "sampling_rate": 1000, "ip4_src": "172.17.0.1", "ip4_dst": "3.0.0.8", "ip4_proto": "17", "sp": "53", "dp": "53", "stamp_inserted": "2021-09-14 16:28:00", "stamp_updated": "2021-09-14 16:29:01", "packets": 571, "bytes": 279790, "writer_id": "default_kafka/9"}

Any advice ? 
Tks
David

**Version**
I'm using latest docker version.

docker images
REPOSITORY       TAG       IMAGE ID       CREATED        SIZE
pmacct/nfacctd   latest    6886b660cfe7   6 months ago   548MB

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment] 2021-09-15 21:25
Hi David ( @door7302 ),

I wonder if would be just matter of setting pmacctd_force_frag_handling (no worries it says `pmacctd`) to true in the config.  Since i am unable to reproduce (a-la, i'd need a brief packet capture from you to do so), not sure if it will make boom everything or make it work everything :-D Can you give it a try?

Truth is that if you would use the built-in L4 primitives - why are you not using them by the way? Did they not work for you? - they would enable fragment handling and unlock "proper" decoding of L4 information. A-la: your trick of offsetting from L3 does work fine because most probably you don't have fragmented traffic.

Paolo

**Comment by door7302** [comment] 2021-09-24 14:28
Hello Paolo,

I tried to set pmacctd_force_frag_handling to true and now native L4 primitives are working for me. Thank you so much for your help. 

BR
David

**Comment by paololucente** [comment] 2021-09-24 16:07
Thank you for confirming David ( @door7302 ). Going to close this issue.

**Closed by paololucente** 2021-09-24 16:07 UTC
