### ISSUE TITLE
Issues with kafka_topic_rr

### ISSUE THREAD

**Issue by remydb** [pmacct/pmacct#84] opened 2016-12-16 14:16 UTC
Hi,

We're currently using nfacct to export flows to kafka, where we consume theme using logstash to push them into elasticsearch. The whole system works like a charm, the only downside at the moment is that nfacct only outputs the flow data to a single topic with a single partition in Kafka. This means only a single logstash instance can connect to the kafka topic to consume the data. I didn't see an option to output to multiple partitions, so the kafka_topic_rr config statement seemed to suffice. I'm trying to run the following config:
```
daemonize: true

plugins: kafka
nfacctd_port: 5678
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, tcpflags, in_iface, out_iface, peer_src_ip, sampling_rate, timestamp_start, timestamp_end, timestamp_arrival
kafka_output: json
kafka_topic: pmacct.acct
kafka_topic_rr: 4
kafka_refresh_time: 10
kafka_history: 1m
kafka_history_roundoff: m
logfile: /var/log/nfacctd.log
```

Using this, the logs look as follows:
```
Dec 16 14:39:18 INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.6.2-git (20161214-01)
Dec 16 14:39:18 INFO ( default/core ):  '--enable-kafka' '--enable-jansson' '--enable-ipv6'
Dec 16 14:39:18 INFO ( default/core ): Reading configuration file '/etc/pmacct/nfacctd.conf'.
Dec 16 14:39:18 INFO ( default/core ): waiting for NetFlow data on :::5678
Dec 16 14:39:18 INFO ( default/kafka ): cache entries=16411 base cache memory=53434216 bytes
Dec 16 14:39:22 INFO ( default/kafka ): *** Purging cache - START (PID: 121530) ***
Dec 16 14:39:22 INFO ( default/kafka ): *** Purging cache - END (PID: 121530, QN: 0/0, ET: 0) ***
Dec 16 14:39:32 INFO ( default/kafka ): *** Purging cache - START (PID: 121554) ***
Dec 16 14:39:32 INFO ( default/kafka ): *** Purging cache - END (PID: 121554, QN: 0/0, ET: 0) ***
Dec 16 14:39:42 INFO ( default/kafka ): *** Purging cache - START (PID: 121582) ***
Dec 16 14:39:52 INFO ( default/kafka ): *** Purging cache - START (PID: 121608) ***
Dec 16 14:40:02 INFO ( default/kafka ): *** Purging cache - START (PID: 121632) ***
Dec 16 14:40:12 INFO ( default/kafka ): *** Purging cache - START (PID: 121663) ***
Dec 16 14:40:22 INFO ( default/kafka ): *** Purging cache - START (PID: 121687) ***
Dec 16 14:40:32 INFO ( default/kafka ): *** Purging cache - START (PID: 121712) ***
Dec 16 14:40:42 INFO ( default/kafka ): *** Purging cache - START (PID: 121829) ***
Dec 16 14:40:44 INFO ( default/kafka ): *** Purging cache - START (PID: 121521) ***
Dec 16 14:40:44 INFO ( default/kafka ): *** Purging cache - END (PID: 121521, QN: 0/0, ET: 0) ***
```

As you can see it ends up just locking up and all the kafka writers just hang. In the end I have to manually kill the core + all the writer processes.
I do see the topics being created in kafka and actually some messages being inserted, only I'm only seeing very low numbers. Where I'd expect to see 10K+ messages every 10 seconds I'm seeing maybe 400 or 500.

Simply removing the `kafka_topic_rr` option makes the whole thing work properly:
```
Dec 16 15:01:29 INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.6.2-git (20161214-01)
Dec 16 15:01:29 INFO ( default/core ):  '--enable-kafka' '--enable-jansson' '--enable-ipv6'
Dec 16 15:01:29 INFO ( default/core ): Reading configuration file '/etc/pmacct/nfacctd.conf'.
Dec 16 15:01:29 INFO ( default/core ): waiting for NetFlow data on :::5678
Dec 16 15:01:29 INFO ( default/kafka ): cache entries=16411 base cache memory=53434216 bytes
Dec 16 15:01:32 INFO ( default/kafka ): *** Purging cache - START (PID: 145069) ***
Dec 16 15:01:32 INFO ( default/kafka ): *** Purging cache - END (PID: 145069, QN: 0/0, ET: 0) ***
Dec 16 15:01:42 INFO ( default/kafka ): *** Purging cache - START (PID: 145160) ***
Dec 16 15:01:45 INFO ( default/kafka ): *** Purging cache - END (PID: 145160, QN: 31835/31835, ET: 1) ***
Dec 16 15:01:52 INFO ( default/kafka ): *** Purging cache - START (PID: 145182) ***
Dec 16 15:01:55 INFO ( default/kafka ): *** Purging cache - END (PID: 145182, QN: 30793/30793, ET: 1) ***
Dec 16 15:02:02 INFO ( default/kafka ): *** Purging cache - START (PID: 145207) ***
Dec 16 15:02:05 INFO ( default/kafka ): *** Purging cache - END (PID: 145207, QN: 31888/31888, ET: 1) ***
```

Version info
nfacct: 1.6.2-git (20161214-01)
kafka: 0.10.1.0 (scala 2.11)
librdkafka: 0.9.2

**Comment by paololucente** [comment] 2016-12-17 12:54
Hi,

You can check CONFIG-KEYS for kafka_partition and kafka_partition_key configuration directives; those would be to play with partitions. Let me know if that would work for you - and suggestions are more than welcome if something is missing.

kafka_topic_rr adds an integer to the topic so that, say, data is written in sprayed over multiple topics, ie. pmacct.acct_0, pmacct.acct_1, pmacct.acct_2, etc., a single different one being used per purge. Regardless, one of two things may be happening here: 1) a bug :) or 2) topics are not automatically created and hence the writers get stuck. I will try to reproduce this and come back to you.

**Comment by remydb** [comment] 2016-12-19 10:29
Hi,

I've only recently started using Kafka, so I'm totally not sure if I've got all this right.. But what I've gathered is that the kafka_partition_key will by default output the messages to the an integer within (% numPartitions), which will then always be the same. What I'm looking for would be to have each message output to either partition 0 or 1 in a round robin fashion, the same way the kafka_topic_rr seems to try to do with topics.

I can confirm that the topics are created for the kafka_topic_rr option and they're nicely spread across my two brokers:
```
root@server:/opt/kafka/bin# ./kafka-topics.sh --zookeeper localhost:2181 --list
nfacct_0
nfacct_1
nfacct_2
nfacct_3

root@server:/opt/kafka/bin# ./kafka-topics.sh --zookeeper localhost:2181 --describe --topic nfacct_0
Topic:nfacct_0  PartitionCount:1        ReplicationFactor:1     Configs:
        Topic: nfacct_0 Partition: 0    Leader: 4       Replicas: 4     Isr: 4
root@server:/opt/kafka/bin# ./kafka-topics.sh --zookeeper localhost:2181 --describe --topic nfacct_1
Topic:nfacct_1  PartitionCount:1        ReplicationFactor:1     Configs:
        Topic: nfacct_1 Partition: 0    Leader: 3       Replicas: 3     Isr: 3
root@server:/opt/kafka/bin# ./kafka-topics.sh --zookeeper localhost:2181 --describe --topic nfacct_2
Topic:nfacct_2  PartitionCount:1        ReplicationFactor:1     Configs:
        Topic: nfacct_2 Partition: 0    Leader: 4       Replicas: 4     Isr: 4
root@server:/opt/kafka/bin# ./kafka-topics.sh --zookeeper localhost:2181 --describe --topic nfacct_3
Topic:nfacct_3  PartitionCount:1        ReplicationFactor:1     Configs:
        Topic: nfacct_3 Partition: 0    Leader: 3       Replicas: 3     Isr: 3
```

Looking at the stats in my Kafka Manager at the moment it does actually seem to work, it's just that each of the 4 topics is only receiving ~1.27 msg/s. That makes for a combined total of ~5 msg/s. If we disable the kafka_topic_rr option and just output to a single topic we insert about 3500msg/s

**Comment by paololucente** [comment] 2016-12-19 13:45
Would it be possible to remotely access your setup? It would speed up the troubleshooting process as reproducing effectively this scenario in lab may take some time and effort. Should i find you positive on the idea, please drop me a private email.

**Comment by paololucente** [comment] 2016-12-23 09:16
aa021a357621b79e3f474ce564242f61f4ba63df belongs to this issue too. Can you please check latest code working for you? Thanks, Paolo

**Comment by johanek** [comment] 2016-12-23 13:46
Hiya

I had the same problem of wanting pmacct to output to multiple partitions for a topic. I know the work here has been related to the topic roundrobin feature, but that's not something I want to use at the moment.

I found that pmacct will write to all the partitions in a topic by setting `kafka_partitions = -1`. This sets `RD_KAFKA_PARTITIONS_UA` in librdkafka, which than handles the partitioning within the library. 

I think this setting was added to pmacct in 1.6.1: https://github.com/pmacct/pmacct/blob/master/ChangeLog#L26

Once I built pmacct 1.6.1 and ran with this setting, output is being written evenly to all partititions across my topic.

**Comment by remydb** [comment] 2016-12-23 13:55
@paololucente The latest code seems to be running great! nfacctd isn't locking up anymore and the output is nicely spread out across 4 topics.

@johanek Thanks for that tip! I'd actually asked Paolo about the possibility of maybe a kafka_partition_rr option, but if setting partitions to -1 already fills all the partitions in a topic then that's kind of redundant. It actually sounds like just what I was looking for!

**Comment by paololucente** [comment] 2016-12-23 14:11
@remydb : thanks very much for confirming. This was very useful also to review the topic creation part. I will close this issue.

@johanek : thanks very much for the tip indeed! Are you actually using a kafka_partition_key as well? Also, do you actually have insight on how the load is being spread evenly by the Kafka partitioner? I ask you because i've tried to research the topic myself a bit and only been able to find fragmented info about hashed partitioning against the key and random partitioning.

**Closed by paololucente** 2016-12-23 14:11 UTC
Labels: bug

**Comment by johanek** [comment] 2016-12-23 17:00
I'm not using a kafka_partition_key, all I'm setting is

```kafka_broker_host: <redacted>
kafka_topic: pmacct
kafka_refresh_time: 60
kafka_history: 1m
kafka_history_roundoff: m
kafka_partition: -1
```

I'm pretty green with kafka, but digging into the librdkafka code turns up this:

Default partitioner is consistent random: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_topic.c#L242

All the magic happens here: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.c#L484

This article was interesting for a background to partitioning, but relates to java: http://www.jakubkorab.net/2015/12/message-distribution-and-topic-partitioning-in-kafka.html

The key bit being 

> It is the client’s responsibility to decide which partition to to send the message to, not the broker’s. This is done by configuring the Producer with an implementation of the Partitioner interface. The default behaviour is to determine the partition via key.hashCode() % numberOfPartitions. By default this will not give fair work sharing for a small set of keys, due to hashing collisions, which means that if you are partitioning to a small number of partitions (for the same number of parallel consumers) some of those partitions are likely to get more messages than the others. In the case of 2 partitions, one might not get any messages at all – leading to consumer starvation. You can balance this out through providing your own Partitioner implementation with a more business-specific partitioning function.

My experience is that the consistent random method is good enough for my use case, which is processing the messages with a number of logstash consumers. 

Here you can see partitions 1-5 are pretty even, after initially only 0 was being written to.

![screen shot 2016-12-23 at 16 35 28](https://cloud.githubusercontent.com/assets/1215863/21458753/08bf300c-c931-11e6-82b2-3565b8dcf6c8.png)

May I suggest that the default setting for `kafka_partitions` be set to -1? I think this is the behaviour most users would be expecting - it's certainly what logstash does for it's kafka output plugin.

**Comment by paololucente** [comment] 2016-12-23 17:06
Hi Johan, that is pretty much what i've read too. Thanks for sharing your results and i agree with your proposal of changing default of kafka_partitions to -1. Can you please open a new issue for that? The concluding one-liner from your previous message would be sufficient as text of the issue.
