### ISSUE TITLE
No Netflow data towards Kafka after upgrade to 1.7.8

### ISSUE THREAD

**Issue by gandraman** [pmacct/pmacct#707] opened 2023-07-21 10:35 UTC
Hello,

we have upgraded pmacct from 1.7.7 to 1.7.8 because of the support for firewall events.
However, we are not receiving any Netflow data in Kafka since the upgrade.

We tried switching back to 1.7.7. with the same configuration and everything works fine (except firewall events as they are available in that version).

Do you know if there could or should be something additional to tweak in the pmacct configuration to make Netflow work in 1.7.8?

Thanks in advance.

Best regards,
Dragan

**Comment by paololucente** [comment] 2023-07-25 00:41
Hi Dragan ( @gandraman ), 

Can you share your config? Could you try also to upgrade to master code to see if that works out well? Nothing known comes to mind that could have a similar effect on functionality.

Paolo

**Comment by paololucente** [comment] 2023-08-02 18:05
Hi Dennis ( @MoreDelay ),

Thanks very much for the follow-up and the extra insight. And i see where this comes from, the examples do contain the quotes (which actually were only meant to say: type what is in between quotes, excluding the quotes). I guess that the notation with the quotes was never real supported, and probably did work before out of luck -- yet i am trying to nail down what commit may have lead to this change in behaviour.

Let me ask you and Dragan ( @gandraman ) the following: is it OK for you to remove the quotes and me fixing / clearing up the examples? Or did the quotes bring any benefits to you guys? I guess not and i guess that once the issue is nailed down you are OK with this resolution -- but i'd like to double-check this with you.

Paolo

**Comment by MoreDelay** [comment] 2023-08-04 08:41
Hi Paolo @paololucente,

yes, we can make do without quotes, that is no problem. Although I find it strange that the parsing still works with quotes sometimes.

As I mentioned, when you only use a single broker and put its address within quotes, it still gets parsed correctly. Personally I do not like undefined behavior and I would prefer if it either "just works" with or without quotes, or fail every time when configured unexpectedly. As I could image there will be a case where people test out a configuration with a single broker and accidentally put it into quotes, which works fine. Then when they scale up and want to add a broker, adding it to the quoted string will run but not connect.

I am not sure how to resolve this issue in the best way, or if it is benign enough to ignore. Perhaps give this a short thought.

Best regards,
Dennis

**Comment by paololucente** [comment] 2023-08-04 17:34
Hi Dennis ( @MoreDelay ),

But help me understanding better: all you did was to upgrade from 1.7.7 to 1.7.8 and the exact same config stopped working? Or, as part of the upgrade, you also upgraded librdkafka and/or switched from one broker to two brokers? Because, i tell you, the string you put in the config (including quotes) is simply stored and passed over to librdkafka (which, in turn, does all the magics with it), it is never handled / interpreted by pmacct.

Paolo

**Comment by paololucente** [comment] 2023-08-08 19:19
Thank you Dennis @MoreDelay , i will then go ahead and close this issue. Paolo

**Closed by paololucente** 2023-08-08 19:19 UTC
