### ISSUE TITLE
nfacct to RabbitMQ to InfuxDB

### ISSUE THREAD

**Issue by nickcn** [pmacct/pmacct#308] opened 2019-08-09 23:12 UTC
Hello,

This is more of a question than an issue. I am trying to set up pmacct (nfacct in particular) to write to InfluxDB using Telegraf ampq_consumer (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/amqp_consumer). I am trying this in a fresh Debian 10 installation using the package from default repos (pmacct version 1.7.2).

This is my nfacctd config:

```
! nfacctd configuration
!
debug: false
!
daemonize: true
pidfile: /var/run/nfacctd.pid
logfile: /var/log/nfacctd/nfacctd.log
syslog: daemon
nfacctd_port: 5678
plugin_buffer_size: 102400
plugin_pipe_size: 10240000
!
aggregate: src_host,dst_host
! on this interface
interface: ens160
!
plugins: amqp
!
amqp_host: localhost
amqp_vhost: /
amqp_user: ****
amqp_passwd: ****
amqp_output: json
amqp_exchange: pmacctd
amqp_routing_key: acct
amqp_exchange_type: direct
amqp_persistent_msg: true
amqp_refresh_time: 60
amqp_history: 5m
amqp_history_roundoff: m
amqp_multi_values: 134217728
amqp_cache_entries: 229397
!
nfacctd_time_new: true
nfacctd_allow_file: /etc/pmacct/routers.lst
networks_file_filter: true
```

My Telegraf config (might be irrelevant but posting in anyway):
```
[[inputs.amqp_consumer]]
  ## Broker to consume from.
  ##   deprecated in 1.7; use the brokers option
  # url = "amqp://localhost:5672/influxdb"

  ## Brokers to consume from.  If multiple brokers are specified a random broker
  ## will be selected anytime a connection is established.  This can be
  ## helpful for load balancing when not using a dedicated load balancer.
  brokers = ["amqp://localhost:5672/"]

  ## Authentication credentials for the PLAIN auth_method.
  username = "****"
  password = "****"

  ## Name of the exchange to declare.  If unset, no exchange will be declared.
  exchange = "pmacctd"

  ## Exchange type; common types are "direct", "fanout", "topic", "header", "x-consistent-hash".
  exchange_type = "direct"

  ## If true, exchange will be passively declared.
  # exchange_passive = false

  ## Exchange durability can be either "transient" or "durable".
  # exchange_durability = "durable"

  ## Additional exchange arguments.
  # exchange_arguments = { }
  # exchange_arguments = {"hash_propery" = "timestamp"}

  ## AMQP queue name
  queue = "pmacct"

  ## AMQP queue durability can be "transient" or "durable".
  queue_durability = "durable"

  ## If true, queue will be passively declared.
  # queue_passive = false

  ## A binding between the exchange and queue using this binding key is
  ## created.  If unset, no binding is created.
  binding_key = "pmacctd"

  ## Maximum number of messages server should give to the worker.
  # prefetch_count = 50

  ## Maximum messages to read from the broker that have not been written by an
  ## output.  For best throughput set based on the number of metrics within
  ## each message and the size of the output's metric_batch_size.
  ##
  ## For example, if each message from the queue contains 10 metrics and the
  ## output metric_batch_size is 1000, setting this to 100 will ensure that a
  ## full batch is collected and the write is triggered immediately without
  ## waiting until the next flush_interval.
  # max_undelivered_messages = 1000

  ## Auth method. PLAIN and EXTERNAL are supported
  ## Using EXTERNAL requires enabling the rabbitmq_auth_mechanism_ssl plugin as
  ## described here: https://www.rabbitmq.com/plugins.html
  # auth_method = "PLAIN"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Content encoding for message payloads, can be set to "gzip" to or
  ## "identity" to apply no encoding.
  # content_encoding = "identity"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
```

The thing is that either nfacct is not sending data to rabbitmq or the telegraf plugin is not able to consume data from rabbitmq. Would it be possible to suggest a way of tackling this?

I can provide any additional info if wanted.

Thank you

**Comment by paololucente** [comment] 2019-08-10 21:53
Hi @nickcn ,

Did you try to set 'debug: true' in nfacctd config? It should make it evident in the logfile whether the plugin is sending out JSON objects onto the RabbitMQ. I may also recommend to check with 'rabbitmqctl list_exchanges' that the exchange 'pmacctd' is really set to 'direct'; and finally i see no mention of routing key 'acct' in the telegraf config.

Paolo 

PS: consider i have never played with Telegraf and my knowledge of RabbitMQ is limited. By the way, curious, why did you prefer RabbitMQ to Kafka?

**Comment by nickcn** [comment] 2019-08-11 11:06
Hello Paolo.

Thank you for your prompt reply.

Regarding your suggestions:

> Did you try to set 'debug: true' in nfacctd config? It should make it evident in the logfile whether the plugin is sending out JSON objects onto the RabbitMQ.

After setting debug to true, all I see in the log is this:
```
2019-08-11T13:56:01+03:00 DEBUG ( default_amqp/amqp ): Connection successful to RabbitMQ: p_amqp_connect_to_publish()
2019-08-11T13:56:01+03:00 INFO ( default_amqp/amqp ): *** Purging cache - START (PID: 63993) ***
2019-08-11T13:56:01+03:00 INFO ( default_amqp/amqp ): *** Purging cache - END (PID: 63993, QN: 0/0, ET: 0) ***
```
Should this be considered normal?

Also:
```
root@traffic:~# rabbitmqctl list_exchanges
Listing exchanges for vhost / ...
amq.direct	direct
	direct
amq.fanout	fanout
amq.rabbitmq.trace	topic
amq.headers	headers
amq.match	headers
amq.topic	topic
telegraf	topic
pmacctd	direct
```
pmaactd exchange is indeed set to direct.

> and finally i see no mention of routing key 'acct' in the telegraf config.

Having put this in telegraf config (in the routing key directive - if I understand correctly), I get no errors in my telegraf log, but still no data pass to influx.

Finally regarding:

> why did you prefer RabbitMQ to Kafka?

I already had a setup with MySQL backend and some scripts to parse and categorize the data, but it seems a PITA to maintain nowadays, so I wanted a more straightforward solution. I plan on trying Kafka next if I have no luck with RabbitMQ.

Waiting for your comments.
Thank you.
Nick

**Comment by paololucente** [comment] 2019-08-11 19:39
Hi @nickcn ,

So definitely the issue is in nfacctd not producing output to RabbitMQ.

Is this a lab / PoC setup with very little traffic? If so one possibility is that data remains trapped in the big buffers and all should resolve by commenting out 'plugin_buffer_size' (you could enable 'debug_internal_msg: true' but it will cause to spit out plenty of info; you could then just turn off buffering instead).

Another possibility is that data is not being read by nfacctd - like a firewall is setup or the system has multiple interfaces and RPF checks are failing, ie. https://github.com/pmacct/pmacct/blob/1.7.2/QUICKSTART#L2490-#L2495 . 

Paolo

**Comment by nickcn** [comment] 2019-08-11 21:52
Hello again.

After disabling buffers and caches and enabling debug_internal_msg, I still get the same message in the logs. I also tried disabling the routers.lst file, but still no luck. As far as the amount of traffic, my env might be a lab, but NetFlow is generated from one of our production routers (I work at an ISP), so I would not consider it to be an issue.

Furthermore, RabbitMQ logs state that nfacctd connects to the service:

```
2019-08-12 00:45:01.979 [info] <0.25499.1> accepting AMQP connection <0.25499.1> ([::1]:47194 -> [::1]:5672)
2019-08-12 00:45:01.993 [info] <0.25499.1> connection <0.25499.1> ([::1]:47194 -> [::1]:5672): user '****' authenticated and granted access to vhost '/'
2019-08-12 00:45:01.998 [info] <0.25499.1> closing AMQP connection <0.25499.1> ([::1]:47194 -> [::1]:5672, vhost: '/', user: '****')
```
Also, after running a tcpdump, I can see that my server receives data at port 5678 correctly.

Is there any requirement on the RabbitMQ server version I might not be aware of?
I have: `{rabbit,"RabbitMQ","3.7.8"}` , straight from Debian's repos.

Any other suggestions/things I could try?
Thank you very much for your time.

**Comment by paololucente** [comment] 2019-08-12 16:45
Hi @nickcn ,

This kind of all confirms that the problem is nfacctd is unable to get input data. The fact you see input packets with tcpdump is on one hand positive (because it means telemetry is reaching your box) but on the other is not a guarantee data is delivered to the application (since, for example, the socket where tcpdump listens is served _before_ filtering). So check that there is no firewall setup; make sure you are not running in the RPF issue i described earlier; not sure if these days SELinux is used anymore (but if so, check that too). The problem looks to be around that area.

Paolo

**Comment by pawmal** [comment] 2019-08-12 22:24
> I am trying to set up pmacct (nfacct in particular) to write to InfluxDB using Telegraf ampq_consumer

Not exatly an answer, but...

Have you considered using print plugin?
I use the following combo: {sf,nf}acctd print plugin with json output, output filename set to named pipe; socat reads from pipe and spawns Python script that repacks pmacct json with minimal changes into InfluxDB using influxdb-python client. Simple, lightweight, works.
(You can skip skip socat and just read from pipe directly, I just prefer that way because it makes Python script one pass thus simpler and easier to modify on the fly).
For Telegraf, I had an idea to use file/pipe input with JSON format, but I was too lazy to configure templates (I use various aggregation criterias) and I also use Python for some data enrichment e.g. if src_as in asn_list then add some custom tag for easier filtering in Grafana.

HTH

**Comment by nickcn** [comment] 2019-08-12 22:57
Hello Paolo,

For some strange reason, the issue seems to these two config directives:
```
nfacctd_allow_file: /etc/pmacct/routers.lst
networks_file_filter: true
```
I still have no clue why, but after commenting them out, the amqp plugin started to work. I will investigate this more tomorrow and comment back.

@pawmal, yes, I have, actually. But I wanted this to be kind of "future-proof". For example, the requirement now is to have only the traffic per IP measured. But what if in a couple of months, if this goes well (like the first try with the MySQL backend), we also want to measure traffic per AS? Having messed with custom scripts on this as I said before, I consider this solution to be more viable in the long term. Maybe I'm right, maybe I'm wrong, who knows.

@paololucente: Regarding the json output, this is what I should expect, right?
{"event_type": "purge", "ip_src": "xxx.xxx.xxx.xxx", "ip_dst": "xxx.xxx.xxx.xxx", "stamp_inserted": "2019-08-13 01:40:00", "stamp_updated": "2019-08-13 01:41:01", "packets": 155, "bytes": 16650, "writer_id": "default_amqp/1665"}

Thank you both for your suggestions.

**Comment by paololucente** [comment] 2019-08-13 17:22
Hi @nickcn , 

Great to see there is progress. The most intuitive question would be: was the IP address of the NetFlow exporter listed in /etc/pmacct/routers.lst ? Also networks_file_filter does not inter-play with nfacctd_allow_file but perhaps - will review code after this - it has a detrimental effect if set to true when an actual networks_file is not defined.

Wrt the JSON output, yes, that is as expected.

Paolo

**Comment by nickcn** [comment] 2019-08-14 09:25
Hello Paolo.

> Also networks_file_filter does not inter-play with nfacctd_allow_file

Why is that? I haven't seen any problems working with them both for about two years now.

Also, if possible, please keep the issue open, because, since I will be on vacation the following days, I won't be able to answer.

Thank you

**Comment by paololucente** [comment] 2019-08-14 14:15
Hi @nickcn , 

Sorry for not having been clear: for (do) "not inter-play" i meant that they do not effect each other. If you remove networks_file_filter, it won't affect in any way nfacctd_allow_file, nfacctd_allow_file is the only one you may need given your config (you do not have a networks_file defined).

This all said, there is zero risk in closing the issue here on GitHub. You can still comment to it afterwards and it can be re-opened. 

Paolo

**Closed** 2019-08-20 14:44 UTC
Labels: question
