### ISSUE TITLE
nfacctd crashing due to malloc assertion

### ISSUE THREAD

**Issue by numbnut** [pmacct/pmacct#490] opened 2021-04-06 08:36 UTC
**Description**
The nfacctd process ran for a long time without any problems and suddenly it started crashing for some hours and was restarted automatically. We weren't able to locate the problem. After some hours the problem vanished. It might be related to some malformed netflow data. Unfortunately I can't share a lot of information, but I still hope that this might help to fix a bug. Since I'm not able to reproduce this I can't test the latest stable version.

**Version**
nfacctd 1.7.5-git (20200510-00+c1) in a custom docker image

**Logs**
```
pmacct_1                     | 2021-03-30T14:38:12.687537082Z INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200510-00+c1)
pmacct_1                     | 2021-03-30T14:38:12.687569742Z INFO ( default/core ):  '--enable-zmq' '--enable-ndpi' '--enable-kafka' '--enable-jansson' '--enable-ipv6' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
...
pmacct_1                     | 2021-03-30T14:38:42.765494725Z nfacctd: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

**Comment by paololucente** [comment] 2021-04-07 16:52
Hi @numbnut , 

Unfortunately, no, this is not sufficient information as it does not say where in nfacctd this happened (only where in malloc.c and that does not help much). I am going to close this Issue but it stays here for the archives in case anybody else does bump in the same / similar. Thanks anyway for reporting it!

Paolo

**Closed** 2021-04-07 16:52 UTC
Labels: mia

**Comment by numbnut** [comment] 2021-04-08 12:01
Hi @paololucente ,
thanks for the response. I still have one question. How can I prepare pmacct to output proper debug information in case of a crash. Why is there no stack trace or something similar in the logs?
I'm not familier with C. Maybe you can point me to the right direction so that when this appears again I have sufficient information at hand.
Regards

**Comment by msune** [comment] 2021-04-08 15:32
@numbnut did you set some hard limit on docker containers mem usage via `-m`?

```
docker run -m 512m
```

In principle, by default, docker containers have no memory nor cpu limits (`unlimited`). What were the specs of the VM or server that was running that container? Can you provide an output of `free -m`?

**Comment by numbnut** [comment] 2021-04-08 15:47
Hi @msune ,
no there are no limits configured. In general there is plenty of memory available and we never had any similar issues during the last years. I will try to investigate a bit further and provide you the numbers.

**Comment by msune** [comment] 2021-04-08 15:50
@numbnut That sounds quite strange

Could you keep monitoring what `docker stats` says on the used memory?

**Comment by msune** [comment] 2021-04-11 19:20
@numbnut If `doker stats` doesn't show anything abnormal before the crash, could you do a run with valgrind?

https://github.com/pmacct/pmacct/blob/master/docs/DOCKER.md#using-valgrind

**Comment by numbnut** [comment] 2021-04-12 10:51
Hi @msune ,
I investigated a bit and have the following rough numbers for you, which confirm my prior statement.
In the time of the crash I observed the following numbers
Memory assigned to pmacct: ~2GB
Free Memory on the System (Free and Cache): ~ 36 GB
Additionally I didn't find any strange numbers in other metrics like CPU usage, network IO etcetera.
From my point of view it looks like a pmacct bug, which might have been triggered by some false input data.

Since I can't reproduce this issue, running pmacct with valgrind doesn't seem like an option for me. I can't apply any invasive operations, since it is a production system. It is still unclear to me how I could improve the logging configuration to have more information at hand, if it happens again. Is this not possible? Again I think running it with valgrind as a default isn't an option.

Thanks for your feedback!

**Comment by paololucente** [comment] 2021-04-12 11:11
Hi @numbnut ,

Agreed on the `valgrind` route since it is not something that can be reproduced short-term. Then you can go down the core dump route ( see: https://github.com/pmacct/pmacct/blob/master/docs/DOCKER.md#core-dumps ): this would generate a coredump file with all needed info for further troubleshooting the issue post-mortem.

Paolo

**Comment by msune** [comment] 2021-04-12 11:47
Agreed with both of you. It doesn't look like a Docker related issue, but possibly a pmacct bug.

>I can't apply any invasive operations, since it is a production system.

As suggested by Paolo, if the system is a production one, then I would suggest to enable coredumps (mind will require the container to be restarted, and follow the instructions there).

**Comment by numbnut** [comment] 2021-04-12 11:54
Hi @paololucente and @msune , thanks for the suggestion. I will take it into consideration and hopefully the next time I am able to provide proper debug information.
