### ISSUE TITLE
[print_plugin] print_history property has no effect

### ISSUE THREAD

**Issue by numbnut** [pmacct/pmacct#250] opened 2018-11-09 13:37 UTC
Hi,
I observed this during upgrading from 1.6.2 to 1.7.1.

On 1.6.2 the following configuration creates 5 files every 5 minutes, which matches the docs.
```
print_refresh_time[netflow]: 300
print_history[netflow]: 1m
print_history_roundoff[netflow]: m
```
After upgrading to 1.7.1 only one file was created. Maybe something major changed, which I'm not aware of, but I didn't find something in the changelog, docs, issues and commit history.
Hope these information are sufficient to reproduce the issue. If this is not the case, please let me know and I will add all the needed information.
Thanks by the way for the great software! Hope this helps to make it even better.

**Comment by paololucente** [comment] 2018-11-21 18:10
Hi @numbnut , thanks for the kind words and apologies for the delay picking this up. I did try to reproduce the issue but i see all working as expected, see:

```
drwx------  2 paolo paolo 65536 Nov 21 18:04 .
drwxr-xr-x 45 paolo paolo 12288 Nov 21 17:58 ..
-rw-------  1 root  root    549 Nov 21 18:02 blabla-20181121-1800.txt
-rw-------  1 root  root    713 Nov 21 18:02 blabla-20181121-1801.txt
-rw-------  1 root  root   1297 Nov 21 18:04 blabla-20181121-1802.txt
-rw-------  1 root  root    831 Nov 21 18:04 blabla-20181121-1803.txt
```

What has changed - and that is documented - is that if in a certain time bin you have no entries to write then the output file is not written anymore (before an empty file was written instead). Is it possible this is the scenario you did run into?

Paolo

**Comment by numbnut** [comment] 2018-11-23 21:59
Hi @paololucente , this is interesting. I now reproduced the issue locally on my dev machine and I will share the configuration that you hopefully are able to reproduce this as well. The case of empty files, which are now not written any more is definitely not the one matching my observation. Please have a look. I use the following Dockerfile to build pmacct.

```
FROM debian:stretch-20181011

EXPOSE 2100

RUN apt-get update && apt-get install -y --no-install-recommends \
    bison \
    build-essential \
    curl \
    ca-certificates \
    flex \
    libreadline-dev \
    libncurses5-dev \
    m4 \
    unzip \
    libpcap-dev \
    libtool \
    automake1.1 \
    autoconf2.13 \
    pkg-config \
    libjansson-dev \
    # manually added
    redis-tools \
    dos2unix \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /etc/pmacct \
  # Use the following lines to build the current head of master
  # && curl -O -L http://www.pmacct.net/pmacct-daily.tar.gz \
  # && tar xf pmacct-daily.tar.gz \
  # && rm pmacct-daily.tar.gz \
  # && cd pmacct-daily \
  && curl -O -L https://github.com/pmacct/pmacct/archive/1.7.1.zip \
  && unzip 1.7.1.zip \
  && rm 1.7.1.zip \
  && cd pmacct-1.7.1 \
  && ./autogen.sh \
  && ./configure --enable-jansson --enable-ipv6 \
  && make \
  && make install

# Add pmacctd config to container
COPY pmacctd.conf /etc/pmacct/pmacctd.conf

# When running pmacct with print plugin:
# Execute nfacctd in foreground
CMD nfacctd -f /etc/pmacct/pmacctd.conf
```
and the following configuration
```
!! General
daemonize:false
nfacctd_port: 2100
nfacctd_time_new: true
plugins: print[netflow]

aggregate[netflow]: tag, src_as, dst_as, sampling_rate, mpls_stack_depth, peer_src_ip, in_iface, peer_dst_ip, as_path, src_as_path, std_comm, src_std_comm, flows, src_port, dst_port, proto, dst_net, src_net, dst_mask, src_mask

plugin_pipe_size[netflow]: 409600000
plugin_buffer_size[netflow]: 40960

!! Print Plugin
print_refresh_time[netflow]: 120
print_history[netflow]: 1m
print_history_roundoff[netflow]: m
print_cache_entries[netflow]: 50000
print_output[netflow]: json
print_output_file[netflow]: /etc/pmacct/netflow/netflow-%Y%m%d-%H%M.json
print_output_file_append[netflow]: true
```
The resulting files look like the following.
```
-rw-------  1 root  staff  1105940 Nov 23 22:42 netflow-20181123-2140.json
-rw-------  1 root  staff   989305 Nov 23 22:44 netflow-20181123-2142.json
-rw-------  1 root  staff  1047396 Nov 23 22:46 netflow-20181123-2144.json
-rw-------  1 root  staff  1222234 Nov 23 22:48 netflow-20181123-2146.json
-rw-------  1 root  staff  1105600 Nov 23 22:50 netflow-20181123-2148.json
-rw-------  1 root  staff  1163643 Nov 23 22:52 netflow-20181123-2150.json
```
As you can see I get one file for two minutes, but I would expect two files for one minute each, which get written every two minutes. Maybe I get something wrong. Hope this helps. Thank you!

**Comment by paololucente** [comment] 2018-11-25 01:43
Hi @numbnut , interesting. For a test can you please comment out plugin_pipe_size and plugin_buffer_size from your config? Guess, for example, buffers are over-sized for the amount of flows received, there could be an artificial delay created within the application. Paolo

**Comment by paololucente** [comment] 2018-11-27 21:51
Hi @numbnut , thanks for the info. There is one thing more that perhaps for you is not time consuming and that would help me further: capture a trace of the output of the traffic generator in libpcap/tcpdump format and share it with me here or via email (it will include timestamps and deltas among each packet so it is possible to simulate also any timing-related issue). This way i can replay in my testbed the output of the generator without having to install it or anything. Let me know if this is possible.

All you should do is: 1) have tcpdump listening in one shell, ie. tcpdump -i <interface> -w <output file> port <UDP port where NetFlow packets are sent to> ; 2) with that done, activate your flow generator and let it complete; 3) press CTRL+C in the tcpdump window so for it to close the output file; 4) send me the tcpdump output file via email.

**Comment by numbnut** [comment] 2018-11-28 09:57
Hi @paololucente , great idea. I will do this as soon as I find some time.

**Comment by numbnut** [comment] 2018-11-28 20:59
I have send you an email with the pcap file. Hope this finally let you reproduce this.

**Comment by paololucente** [comment] 2018-12-06 11:50
Hi @numbnut , the issue is just fixed - see the committed piece of code above. It would be wonderful if you could give it a try and confirm it working for you. Paolo

**Comment by numbnut** [comment] 2018-12-09 22:33
Hi @paololucente , I can confirm that this is fixed on the current master branch. Thank you very much. This issue may be closed.

**Closed** 2018-12-09 22:50 UTC
Labels: bug
