### ISSUE TITLE
Issues with sfacctd Docker container

### ISSUE THREAD

**Issue by SanderDelden** [pmacct/pmacct#451] opened 2020-12-10 23:10 UTC
**Description**
We are currently using a custom build docker image where pmacct 1.7.2 is installed using apt, as we want to upgrade to the latest version of pmacct we decided to use the official Docker images. Unfortunately after a minute or so the container exits with:

`free(): invalid next size (fast)`

With debug logging enabled no additional information is shown.

Our sfacctd.conf is as follows:
```
plugins: print[DSTAS],print[SRCAS]

bgp_daemon: true
bgp_daemon_max_peers: 20
bgp_agent_map:/etc/pmacct/mappings/bgp.map
nfacctd_as_new: bgp
sfacctd_port: 5008
sfacctd_renormalize: true
pre_tag_map:/etc/pmacct/mappings/pretag.map

pre_tag_filter[DSTAS]: -1
aggregate [DSTAS]: label, dst_as, peer_dst_as, out_iface
print_output_file[DSTAS]: /tmp/5m_DSTAS.json
print_output[DSTAS]: json
print_refresh_time[DSTAS]: 60
plugin_pipe_size[DSTAS]: 10240000
plugin_buffer_size[DSTAS]: 30240
print_output_file_append[DSTAS]: true
print_trigger_exec[DSTAS]: /etc/pmacct/scripts/send2influx_DSTAS.py

pre_tag_filter[SRCAS]: -1
aggregate [SRCAS]: label, src_as, peer_src_as, in_iface
print_output_file[SRCAS]: /tmp/5m_SRCAS.json
print_output[SRCAS]: json
print_refresh_time[SRCAS]: 60
plugin_pipe_size[SRCAS]: 10240000
plugin_buffer_size[SRCAS]: 30240
print_output_file_append[SRCAS]: true
print_trigger_exec[SRCAS]: /etc/pmacct/scripts/send2influx_SRCAS.py
```

Our Dockerfile is as follows:
```
FROM pmacct/sfacctd

RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        procps \
        && rm -rf /var/lib/apt/lists/*

RUN pip3 install influxdb
RUN bash -c 'mkdir -p /etc/pmacct/{scripts,info}'

COPY pmacct/mappings/*.map /etc/pmacct/mappings/
COPY pmacct/scripts/*.py /etc/pmacct/scripts/
COPY pmacct/configs/*.conf /etc/pmacct/
```

Please let me know if any additonal information is required!

**Version**
1.7.5
For what it's worth, the same issue occurs when using the bleeding-edge version.

**Comment by msune** [comment] 2020-12-11 17:47
@SanderDelden Two question wrt to this:

a) Are you running the container with a specific memory limit setting? Official docker containers are compiled with all plugins supported, so memory footprint might be _slightly_ different than you previous custom container. If it's dramatic, that could also be considered a bug (@paololucente?).
b) Could you attach `sfacctd` logs during the crashed execution?
c) Could you temporally run `sfacctd` with `valgrind`?

Perhaps pointing the obvious, specially for c), please use your container based on vanilla `sfacctd`, but override the entry point:

```
# docker run -it --entrypoint bash 
<container_id># valgrind sfacctd <your options>
```

**Comment by SanderDelden** [comment] 2020-12-14 14:57
Hi @msune thank you for your swift reply!

a) The container for pmacct (or any for that matter) has no memory limits, the host has 128GB and is not running out of memory.
b) See sfacctd.log
c) See sfacctd-valgrind.log

[sfacctd.log](https://github.com/pmacct/pmacct/files/5689522/sfacctd.log)
[sfacctd-valgrind.log](https://github.com/pmacct/pmacct/files/5689523/sfacctd-valgrind.log)

**Comment by msune** [comment] 2020-12-14 18:37
It looks like the culprit is the conditional jump at the end, but these invalid accesses are also tricky:

```
INFO ( default/core/BGP ): [xx.xx.xx.255] BGP_OPEN: Local AS: 12345 Remote AS: 12345 HoldTime: 180
==1== Invalid write of size 1
==1==    at 0x17C2A3: pretag_copy_label (pretag.c:791)
==1==    by 0x182884: pretag_label_handler (pretag_handlers.c:2317)
==1==    by 0x17C5F7: pretag_entry_process (pretag.c:867)
==1==    by 0x140616: SF_find_id (sfacctd.c:2119)
==1==    by 0x14E54A: exec_plugins (plugin_hooks.c:401)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==  Address 0x1a9c16e9 is 0 bytes after a block of size 25 alloc'd
==1==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==1==    by 0x17C187: pretag_malloc_label (pretag.c:750)
==1==    by 0x17C287: pretag_copy_label (pretag.c:784)
==1==    by 0x182884: pretag_label_handler (pretag_handlers.c:2317)
==1==    by 0x17C5F7: pretag_entry_process (pretag.c:867)
==1==    by 0x140616: SF_find_id (sfacctd.c:2119)
==1==    by 0x14E54A: exec_plugins (plugin_hooks.c:401)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==
==1== Conditional jump or move depends on uninitialised value(s)
==1==    at 0x483931D: __strncpy_sse2_unaligned (vg_replace_strmem.c:554)
==1==    by 0x17C29C: pretag_copy_label (pretag.c:790)
==1==    by 0x17C6F8: pretag_entry_process (pretag.c:893)
==1==    by 0x140616: SF_find_id (sfacctd.c:2119)
==1==    by 0x14E54A: exec_plugins (plugin_hooks.c:401)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==
==1== Invalid write of size 1
==1==    at 0x17C2A3: pretag_copy_label (pretag.c:791)
==1==    by 0x17C6F8: pretag_entry_process (pretag.c:893)
==1==    by 0x140616: SF_find_id (sfacctd.c:2119)
==1==    by 0x14E54A: exec_plugins (plugin_hooks.c:401)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==  Address 0x1a9c174a is 0 bytes after a block of size 26 alloc'd
==1==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==1==    by 0x17C187: pretag_malloc_label (pretag.c:750)
==1==    by 0x17C287: pretag_copy_label (pretag.c:784)
==1==    by 0x17C6F8: pretag_entry_process (pretag.c:893)
==1==    by 0x140616: SF_find_id (sfacctd.c:2119)
==1==    by 0x14E54A: exec_plugins (plugin_hooks.c:401)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==
==1== Conditional jump or move depends on uninitialised value(s)
==1==    at 0x483931D: __strncpy_sse2_unaligned (vg_replace_strmem.c:554)
==1==    by 0x14BBAD: vlen_prims_insert (util.c:2596)
==1==    by 0x14E6CE: exec_plugins (plugin_hooks.c:443)
==1==    by 0x141797: process_SFv5_packet (sfacctd.c:1495)
==1==    by 0x13F5AB: main (sfacctd.c:1355)
==1==
```

`Conditional jump or move depends on uninitialised value(s)` might be the reason why you see it in the official containers and not in yours, as perhaps, by pure luck, your custom Docker container has _the right_ value most/all of the executions, due to the compiled-in plugins being different, flags, scheduling etc...

If you have the time, you could run the same exact `valgrind sfacctd <youroptions>` command in your container, and comment if you see the same invalid accesses and conditional jump warning, along with the flags (DEBUG/NDEBUG) and the plugins compiled in. That will give extra info to fix the issue.

In any case, this is a bug in main codebase, and it is not related with the Dockerization. @paololucente

**Comment by SanderDelden** [comment] 2020-12-14 19:04
Just ran the (working) container with valgrind have attached the logs from this. No conditional jumps are observed there, however I do notice the "Invalid write" errors.  The Dockerfile for this container looks as follows:
```
FROM debian:buster

# Install required packages
RUN apt-get update && apt-get install -y \
        pmacct \
        python3 \
        python3-pip \
        procps \
        valgrind \
        && rm -rf /var/lib/apt/lists/*

# PIP Install InfluxDB
RUN pip3 install influxdb

# Create required folders for pmacct
RUN bash -c 'mkdir -p /etc/pmacct/{configs,scripts,info}'

# Copy configs files to pmacct directories
COPY pmacct/mappings/bgp.map pmacct/mappings/tags/*as_pretag.map /etc/pmacct/mappings/
COPY pmacct/scripts/*.py /etc/pmacct/scripts/
COPY pmacct/configs/sfacctd.conf /etc/pmacct/configs/

# Start pmacct
ENTRYPOINT ["/usr/bin/valgrind"]
CMD ["sfacctd", "-f", "/etc/pmacct/configs/sfacctd.conf"]
```
[sfacctd.log](https://github.com/pmacct/pmacct/files/5690993/sfacctd.log)

Please let me know if any additonal information is required!

**Comment by paololucente** [comment] 2020-12-15 11:50
Hi @SanderDelden ,

I did an analysis of your Valgrind output (thanks for providing that). While i can't reproduce myself your issue (the fact that it does happen after a bit may suggest it is input related), i may be on the good track to identify the root cause. If you see above, i made a commit referencing this issue. Can you please run latest bleeding-edge container and see if it keeps crashing and, if yes, do another round of Valgrind?

I beg apologies in advance i suspect resolving this issue may take a few more iterations.

Paolo

**Comment by SanderDelden** [comment] 2020-12-15 16:13
Hi @paololucente ,

Thank you very much for your reply. I've run the bleeding-edge version and still run into the same issue, logs have been attached again.

Also, no apologies necessary, I think it's great that you are willing to help out with this :)

[Uploading sfacctd-bleedingedge-valgrind.log…]()

**Comment by paololucente** [comment] 2020-12-16 22:55
Hi @SanderDelden ,

I could reproduce the “Invalid write of size 1” and “is 0 bytes after a block of size X alloc’d” part but not the “Conditional jump or move depends on uninitialised value(s)” one. I solved what i could reproduce with the latest commit - i am now wondering (hoping?) whether there is a cause/effect connection among the two. Can you do one more iteration? Test the latest container working and, if not, pass it under valgrind?

Paolo

**Comment by SanderDelden** [comment] 2020-12-18 13:02
Hi @paololucente ,

Unfortunately not working yet, did another iteration with Valgrind and logs have been attached as requested. I noticed the tracebacks from the python scripts triggered by pmacct, it seems these are being caused due to characters being appended to the labels. As you can see on line 182: bb11-ams1.xxxxxx.nl**2** the 2 should not be here. On line 230 the 0 should not be present. Could this maybe be the result of the memory errors? Or would this be an entirely different problem?

These tracebacks were also present earlier, my apologies for not including them before, thought it wasn't relevant.

Let me know if you require any additional information!
[sfacctd-valgrind.log](https://github.com/pmacct/pmacct/files/5715782/sfacctd-valgrind.log)

**Comment by paololucente** [comment] 2020-12-18 15:05
Hi @SanderDelden ,

From your latest log i see that you did not refresh the container. "sfacctd 1.7.6-git (20201215-0 (2b55814))" whereas we are aiming at the code from the day after, 20201216-0 (c3823e2). Is it possible, does this ring a bell?

**Comment by SanderDelden** [comment] 2020-12-18 15:22
Hi @paololucente ,

Don't know how that happended to be honest, rebuild the containers as usual. My apologies for the inconvenience.

I just rebuild everything from scratch and it seems like the issue has been resolved! Many many thanks for your help with this :)

**Closed** 2020-12-18 15:22 UTC
