### ISSUE TITLE
migrating from quagga: frr bgp & pmacct

### ISSUE THREAD

**Issue by acoul** [pmacct/pmacct#549] opened 2021-11-30 13:31 UTC
Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git [20200925-0 (d117ad0a)]

Arguments:
 '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.10.1 (with TPACKET_V3)

System:
Linux 5.15.5-gentoo  SMP Sat Nov 27 11:09:08 EET 2021 i686

Compiler:
gcc 10.2.0

Greetings,

this is **NOT** a bug, rather than an issue concerning FRR bgpd, thereof I am filing it here as a reference.

Migrating from Quagga bgpd to FRR bgpd I was beaten by [this issue](https://github.com/FRRouting/frr/issues/10153)

FWIW, I was able to overcome this issue using [redir](https://github.com/troglobit/redir) on a different server on the same lan

**Comment by paololucente** [comment] 2021-12-01 20:19
Hi Alexandros ( @acoul ),

Thanks very much for filing this. I have labelled it as cross-reference. I propose to let's keep it open until the FRR side is somehow resolved / concluded.

Paolo

**Comment by rodecker** [comment] 2022-03-07 17:16
Hello,

I did some testing with pmacct and FRR. FRR commit [4122b697bbe16dc90a56e4d5597a203a7d31a494](https://github.com/FRRouting/frr/pull/10357/commits/4122b697bbe16dc90a56e4d5597a203a7d31a494) makes it possible to start pmacct and FRR on the same host. There are a few caveats though:

* FRR by default listens on all interfaces (:: and 0.0.0.0). With this configuration it will not allow you to configure the pmacct neighbor, even if it is listening on a different port. Configure FRR's `bgpd_options` to listen on some IP addresses and set a different address as pmacct's `bgp_daemon_ip`.

* FRR cannot initiate BGP sessions from 127.0.0.1 or ::1. When setting pmacct's `bgp_daemon_ip` to ::2 and FRR's `update-source` to ::1 the BGP session will not come up. FRR's log will show `::2: nexthop_set failed, resetting connection - intf 0x0`. Setting pmacct's `bgp_daemon_ip` to ::1 and FRR's `update-source` to ::2 does work, as does setting both to ::2.

Example config:

```
! pmacctd.conf
bgp_daemon: true
bgp_daemon_ip: ::1
bgp_daemon_port: 180
bgp_daemon_max_peers: 1
!
```

```
! frr.conf
router bgp 65001
  bgp router-id 10.0.0.1
  bgp ebgp-requires-policy
  bgp log-neighbor-changes
  neighbor ::1 remote-as 65001
  neighbor ::1 port 180
  neighbor ::1 update-source ::2
!
  address-family ipv4 unicast
    neighbor ::1 activate
!
  address-family ipv6 unicast
    neighbor ::1 activate
!
```

I hope this helps others wanting to use pmacct and FRR together.

**Comment by paololucente** [comment] 2022-03-08 18:37
Hi Martin ( @rodecker ),

Thanks for adding this bit of info, much appreciated! There is one section of documentation ( here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1359-L1416 ) where the issue is scratched wrt Bird and Quagga (re-reading it, i did not like it much that the two notes are mixed up, to be straightened up): would you like (or may i ask you the favor) to contribute some text for this section wrt FRR? Even just dump what you wrote above in the document?

Paolo

**Comment by rodecker** [comment] 2022-03-09 10:18
Hi @paololucente ,

I have added my notes on FRR and restructured the section a bit. See above.

Cheers,
Martin

**Comment by paololucente** [comment] 2022-03-10 01:57
Thank you so much @rodecker , just merged.

**Comment by rodecker** [comment] 2022-03-15 16:35
FYI, frr 8.2.2 was released this morning. This includes the fix (though this is not mentioned in the changelog).

https://github.com/FRRouting/frr/releases/tag/frr-8.2.2

**Comment by paololucente** [comment] 2022-03-15 17:42
Wonderful, thanks for the note @rodecker ! I'd then go ahead and close this issue.

**Closed** 2022-03-15 17:42 UTC
Labels: cross-reference
