### ISSUE TITLE
On platforms with reuseport support the reuseaddr option isn't set

### ISSUE THREAD

**Issue by eduarrrd** [pmacct/pmacct#517] opened 2021-07-23 21:52 UTC
**Description**
Throughout the codebase there are snippets like this (example from `src/sfacctd.c`):

```c
#if (defined HAVE_SO_REUSEPORT)
    rc = setsockopt(config.sock, SOL_SOCKET, SO_REUSEADDR|SO_REUSEPORT, (char *) &yes, (socklen_t) sizeof(yes));
    if (rc < 0) Log(LOG_ERR, "WARN ( %s/core ): setsockopt() failed for SO_REUSEADDR|SO_REUSEPORT.\n", config.name);
#else
    rc = setsockopt(config.sock, SOL_SOCKET, SO_REUSEADDR, (char *) &yes, (socklen_t) sizeof(yes));
    if (rc < 0) Log(LOG_ERR, "WARN ( %s/core ): setsockopt() failed for SO_REUSEADDR.\n", config.name);
#endif
```

The option_name argument to `setsockopt(3)` represents only a single option. The underlying enum values are not composable (https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/socket.h#L11). This can further be verified using e.g. `strace(1)`.

In the specific case of `SO_REUSEADDR|SO_REUSEPORT` we're evaluating `2 | 15` which is `15` which is just `SO_REUSEPORT`.

Based on https://sourcegraph.com/search?q=context:global+SO_REUSEADDR%7CSO_REUSEPORT+repo:pmacct/pmacct&patternType=literal there are at least 7 instance of the above.

My suggestion would be to rewrite the above snippets to something like

```c
#if (defined HAVE_SO_REUSEPORT)
    rc = setsockopt(config.sock, SOL_SOCKET, SO_REUSEPORT, (char *) &yes, (socklen_t) sizeof(yes));
    if (rc < 0) Log(LOG_ERR, "WARN ( %s/core ): setsockopt() failed for SO_REUSEPORT.\n", config.name);
#endif
    rc = setsockopt(config.sock, SOL_SOCKET, SO_REUSEADDR, (char *) &yes, (socklen_t) sizeof(yes));
    if (rc < 0) Log(LOG_ERR, "WARN ( %s/core ): setsockopt() failed for SO_REUSEADDR.\n", config.name);
```

**Version**
First observed on 1.7.6, still present on master as the time of writing.

**Comment by paololucente** [comment] 2021-07-25 17:06
Thanks @eduarrrd for spotting the problem and proposing a fix to it. I've just committed your proposed changes, just let me know if now everything works as intended for you. Paolo

**Closed** 2021-07-30 16:40 UTC
Labels: bug
