### ISSUE TITLE
Garbage in nfacct output

### ISSUE THREAD

**Issue by ElizavetaFirst** [pmacct/pmacct#439] opened 2020-11-02 17:07 UTC
**Description**
Hi  Paolo!

When Netflow v9 traffic without templates arrived, I receive garbage in nfacct  output.
For example: {"event_type": "purge", "class": "unknown", "mac_src": "00:00:00:00:00:00", "mac_dst": "00:00:00:00:00:00", "vlan": 0, "peer_ip_src": "<real ip>", "iface_in": 3904592445, "iface_out": 3904592445, "ip_src": "0.0.4.244", "ip_dst": "0.0.6.113", "port_src": 0, "port_dst": 0, "tcp_flags": "0", "ip_proto": "0", "timestamp_start": "2020-09-13 07:08:52.000000", "timestamp_end": "2020-09-11 09:03:34.000000", "timestamp_arrival": "2020-11-02 19:27:03.061206", "packets": 4294967676, "bytes": 748525161065989222}

Also for this peer_ip_src value I can see such logs in nfacctd.log: 
2020-11-02T19:27:02+03:00 DEBUG ( default/core ): Received NetFlow/IPFIX packet from [<real ip>:50101] version [10] seqno [430688199]
2020-11-02T19:27:02+03:00 DEBUG ( default/core ): Discarded NetFlow v9/IPFIX packet (R: unknown template 256 [<real ip>:526337])

When I send header to pmacct from my app, I send query header type as  WANT_STATS | WANT_ERASE.

I expect that in case when template is absent there will be no output.
Could can you answer what i am doing wrong?

Thanks in advance!

**Version**
1.7.5

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment] 2020-11-02 23:46
Hi @ElizavetaFirst ,

Your output is intriguing. Can you say if this is a binary that you did compile yourself? Can you show me the print out of a "nfacctd -V"? Finally can you please share your full config (it's OK to mask sensible data)? 

Paolo

**Comment by ElizavetaFirst** [comment] 2020-11-03 08:35
> Hi @ElizavetaFirst ,
> 
> Your output is intriguing. Can you say if this is a binary that you did compile yourself? Can you show me the print out of a "nfacctd -V"? Finally can you please share your full config (it's OK to mask sensible data)?
> 
> Paolo

Hello Paolo!
Yes, I compiled this binary by myself with next steps:
sh autogen.sh
./configure --enable-jansson
make

Output nfacctd -V:

NetFlow Accounting Daemon, nfacctd 1.7.5-git (20200510-00+c1)

Arguments:
 '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-jansson' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
jansson 2.10

System:
Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64

Compiler:
gcc 4.8.5

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.



Config:
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys supported ?
!
! General configs
!
daemonize: false
logfile: /ARCHIVE/logs/nf-sniffer/nfacctd.log
imt_path: /tmp/nf-collect.pipe
debug: true
!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: <port>
nfacctd_templates_file: /ARCHIVE/netflow_templates.dat
!
! Plugins definitions
!
!plugins: memory[inmemory_db]
plugins: print[inmemory_db]


print_refresh_time[inmemory_db]: 10
print_history[inmemory_db]: 30
print_history_roundoff[inmemory_db]: m
print_output_file_append[inmemory_db]: true
print_output_file[inmemory_db]: /ARCHIVE/logs/nf-sniffer/stat.log
print_output[inmemory_db]: json

!
! Pipe and shared memory buffer size between plugin and nfacctd receiver
plugin_pipe_size: 18192000
plugin_buffer_size: 18192
!
! Internal DB pools parameters
imt_mem_pools_size: 1024000
imt_mem_pools_number: 1024


!
!
! 'inmemory_db' plugin configuration
!
! aggregate option sets which data should be collected and stored in db
! All allowed options for aggregate:
!aggregate[inmemory_db]: src_mac, dst_mac, vlan, cos, etype, src_host, dst_host, src_net, dst_net, src_mask, dst_mask, src_as, dst_as, src_port, dst_port, tos, proto, none, sum_mac, sum_host, sum_net, sum_as, sum_port, flows, tag, tag2, label, class, tcpflags, in_iface, out_iface, std_comm, ext_comm, lrg_comm, as_path, peer_src_ip, peer_dst_ip, peer_src_as, peer_dst_as, local_pref, med, src_std_comm, src_ext_comm, src_lrg_comm, src_as_path, src_local_pref, src_med, mpls_vpn_rd, mpls_pw_id, mpls_label_top, mpls_label_bottom, mpls_stack_depth, sampling_rate, sampling_direction, src_host_country, dst_host_country, src_host_pocode, dst_host_pocode, src_host_coords, dst_host_coords, nat_event, post_nat_src_host, post_nat_dst_host, post_nat_src_port, post_nat_dst_port, tunnel_src_host, tunnel_dst_host, tunnel_proto, tunnel_tos, timestamp_start, timestamp_end, timestamp_arrival, export_proto_seqno, export_proto_version, export_proto_sysid
!
aggregate[inmemory_db]: src_host, src_port, dst_host, dst_port, proto, timestamp_start, timestamp_end, timestamp_arrival, tcpflags, peer_src_ip, vlan, in_iface, out_iface, src_mac, dst_mac

**Comment by paololucente** [comment] 2020-11-03 13:12
As a test, can you please remove 'nfacctd_templates_file' from the config? I bet that is what is creating the issue there. If confirmed a next step would be to understand why, ie. do the templates tend to change often? Or is it a bug?

**Comment by ElizavetaFirst** [comment] 2020-11-03 13:21
> As a test, can you please remove 'nfacctd_templates_file' from the config? I bet that is what is creating the issue there. If confirmed a next step would be to understand why, ie. do the templates tend to change often? Or is it a bug?

I deleted nfacctd_templates_file before test.
But it created again with such records for this src:
{"agent": "<real ip>", "source_id": 2193, "template_id": 1025, "template_type": 0, "num": 23, "len": 65, "vlen": 0, "list": [{"type": 0, "otpl": {"off": 0, "len": 4, "tpl_len": 4, "tpl_index": 2}}, {"type": 0, "otpl": {"off": 4, "len": 4, "tpl_len": 4, "tpl_index": 1}}, {"type": 0, "otpl": {"off": 8, "len": 4, "tpl_len": 4, "tpl_index": 8}}, {"type": 0, "otpl": {"off": 12, "len": 4, "tpl_len": 4, "tpl_index": 12}}, {"type": 0, "otpl": {"off": 16, "len": 4, "tpl_len": 4, "tpl_index": 10}}, {"type": 0, "otpl": {"off": 20, "len": 4, "tpl_len": 4, "tpl_index": 14}}, {"type": 0, "otpl": {"off": 24, "len": 4, "tpl_len": 4, "tpl_index": 21}}, {"type": 0, "otpl": {"off": 28, "len": 4, "tpl_len": 4, "tpl_index": 22}}, {"type": 0, "otpl": {"off": 32, "len": 2, "tpl_len": 2, "tpl_index": 7}}, {"type": 0, "otpl": {"off": 34, "len": 2, "tpl_len": 2, "tpl_index": 11}}, {"type": 0, "otpl": {"off": 36, "len": 4, "tpl_len": 4, "tpl_index": 16}}, {"type": 0, "otpl": {"off": 40, "len": 4, "tpl_len": 4, "tpl_index": 17}}, {"type": 0, "otpl": {"off": 44, "len": 4, "tpl_len": 4, "tpl_index": 18}}, {"type": 0, "otpl": {"off": 48, "len": 1, "tpl_len": 1, "tpl_index": 9}}, {"type": 0, "otpl": {"off": 49, "len": 1, "tpl_len": 1, "tpl_index": 13}}, {"type": 0, "otpl": {"off": 50, "len": 1, "tpl_len": 1, "tpl_index": 4}}, {"type": 0, "otpl": {"off": 51, "len": 1, "tpl_len": 1, "tpl_index": 6}}, {"type": 0, "otpl": {"off": 52, "len": 1, "tpl_len": 1, "tpl_index": 5}}, {"type": 0, "otpl": {"off": 53, "len": 1, "tpl_len": 1, "tpl_index": 61}}, {"type": 0, "otpl": {"off": 54, "len": 1, "tpl_len": 1, "tpl_index": 89}}, {"type": 0, "otpl": {"off": 55, "len": 2, "tpl_len": 2, "tpl_index": 48}}, {"type": 0, "otpl": {"off": 57, "len": 4, "tpl_len": 4, "tpl_index": 234}}, {"type": 0, "otpl": {"off": 61, "len": 4, "tpl_len": 4, "tpl_index": 235}}]}
{"agent": "<real ip>2", "source_id": 2081, "template_id": 1025, "template_type": 0, "num": 24, "len": 87, "vlen": 0, "list": [{"type": 0, "otpl": {"off": 0, "len": 8, "tpl_len": 8, "tpl_index": 2}}, {"type": 0, "otpl": {"off": 8, "len": 8, "tpl_len": 8, "tpl_index": 1}}, {"type": 0, "otpl": {"off": 16, "len": 4, "tpl_len": 4, "tpl_index": 8}}, {"type": 0, "otpl": {"off": 20, "len": 4, "tpl_len": 4, "tpl_index": 12}}, {"type": 0, "otpl": {"off": 24, "len": 4, "tpl_len": 4, "tpl_index": 10}}, {"type": 0, "otpl": {"off": 28, "len": 4, "tpl_len": 4, "tpl_index": 14}}, {"type": 0, "otpl": {"off": 32, "len": 4, "tpl_len": 4, "tpl_index": 21}}, {"type": 0, "otpl": {"off": 36, "len": 4, "tpl_len": 4, "tpl_index": 22}}, {"type": 0, "otpl": {"off": 40, "len": 2, "tpl_len": 2, "tpl_index": 7}}, {"type": 0, "otpl": {"off": 42, "len": 2, "tpl_len": 2, "tpl_index": 11}}, {"type": 0, "otpl": {"off": 44, "len": 4, "tpl_len": 4, "tpl_index": 16}}, {"type": 0, "otpl": {"off": 48, "len": 4, "tpl_len": 4, "tpl_index": 17}}, {"type": 0, "otpl": {"off": 52, "len": 4, "tpl_len": 4, "tpl_index": 18}}, {"type": 0, "otpl": {"off": 56, "len": 1, "tpl_len": 1, "tpl_index": 9}}, {"type": 0, "otpl": {"off": 57, "len": 1, "tpl_len": 1, "tpl_index": 13}}, {"type": 0, "otpl": {"off": 58, "len": 1, "tpl_len": 1, "tpl_index": 4}}, {"type": 0, "otpl": {"off": 59, "len": 2, "tpl_len": 2, "tpl_index": 6}}, {"type": 0, "otpl": {"off": 61, "len": 1, "tpl_len": 1, "tpl_index": 5}}, {"type": 0, "otpl": {"off": 62, "len": 1, "tpl_len": 1, "tpl_index": 61}}, {"type": 0, "otpl": {"off": 63, "len": 4, "tpl_len": 4, "tpl_index": 89}}, {"type": 0, "otpl": {"off": 67, "len": 4, "tpl_len": 4, "tpl_index": 302}}, {"type": 0, "otpl": {"off": 71, "len": 4, "tpl_len": 4, "tpl_index": 234}}, {"type": 0, "otpl": {"off": 75, "len": 4, "tpl_len": 4, "tpl_index": 235}}, {"type": 0, "otpl": {"off": 79, "len": 8, "tpl_len": 8, "tpl_index": 198}}]}

But all logs what I can see in nfacct.log says that for all packets with this source are discarded.

**Comment by paololucente** [comment] 2020-11-04 14:06
Hi @ElizavetaFirst ,

If you removed the nfacctd_templates_file directive from the config, it should not be re-creating the file. Just to make sure, i was suggesting to edit the config and remove the line (not remove the file which, if nfacctd_templates_file is removed from the config, would be ignored anyway).

NetFlow v9/IPFIX is a template-based protocol. Until a template is received it is normal to get packet discarded; just wait a few seconds or minutes. This is a condition that you will find only at start up of the application. 

Paolo

**Comment by ElizavetaFirst** [comment] 2020-11-05 07:51
Hi Paolo.

I deleted the line and effect is the same: I see garbage in output.

Why, when we discard a packet without a template, it still comes?
Maybe I forget some settings, or it is correct behavior?

Best regards,
Elizaveta

**Comment by paololucente** [comment] 2020-11-06 17:28
Any chance there is some old nfacctd instance still running? Like if you do a 'killall -9 nfacctd', restart nfacctd without nfacctd_templates_file in the config - do you still the issue? If so this is totally weird.

**Comment by ElizavetaFirst** [comment] 2020-11-06 18:34
> Any chance there is some old nfacctd instance still running? Like if you do a 'killall -9 nfacctd', restart nfacctd without nfacctd_templates_file in the config - do you still the issue? If so this is totally weird.

Hello Paolo!

Yes, I still have the issue, even after killing all instances.
Now I probably will patch the pmacct to fix this problem. I Overviewed the code and don't anderstand wery well how nfacctd communicates with nfacct core and how nfacct core understand that packets from nfacctd a ready for reading from shared memory.
In process_v9_packet function we can see in arguments struct packet_ptrs_vector *pptrsv. As I can see, it is pointer to part which manage shared memory and we fill some fields in this function and read it somewhere in other process.
When I try to comment this part:
  pptrsv->v4.f_status = (u_char *) nfv9_check_status(pptrs, SourceId, 0, FlowSeq, TRUE);
  set_vector_f_status(pptrsv);
  pptrsv->v4.f_status_g = (u_char *) nfv9_check_status(pptrs, 0, NF9_OPT_SCOPE_SYSTEM, 0, FALSE);
  set_vector_f_status_g(pptrsv);
I stop getting garbage values in the output.
But I stop gettting values in the output at all)))
It's very difficult to very to figure out a 1000 line function with goto and other wonderful things.:)
 Also I have no much experience in work with shared memory.
So, could you tell me where to pay special attention?

Best regards,
Elizaveta

**Comment by paololucente** [comment] 2020-11-07 13:25
Hi @ElizavetaFirst ,

Probably quicker, since this looks something basic: i may offer to have a look at the issue myself on your system. If that is a possibility, let's sync-up by private email on login and stuff. 

Paolo

**Comment by ElizavetaFirst** [comment] 2020-11-07 14:26
Hello @paololucente!
Could you write me your email to contact?
Or you can write me to email tsibereva@gmail.com.

**Comment by paololucente** [comment] 2020-11-07 15:01
https://github.com/pmacct/pmacct/blob/master/AUTHORS#L6

**Comment by paololucente** [comment] 2020-11-13 15:50
Hi @ElizavetaFirst , 

Not having heard from you since, i am closing this issue. We can always re-open later and/or update the comments here.

Paolo

**Closed by paololucente** 2020-11-13 15:50 UTC
