### ISSUE TITLE
nfacctd: IPFIX packets received, but nothing is written to memory/print plugin

### ISSUE THREAD

**Issue by trolyara** [pmacct/pmacct#326] opened 2019-10-02 08:39 UTC
pmacct 1.7.3 (compiled from sources) is installed on CentOS 6.

For initial setup and debugging we started the collector in a simple configuration:

`nfacctd -l 3995 -P print -d`

Debug log shows that multiple ipfix packets (templates and flows) are recieved:

`DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x:y] version [10] seqno [857437]`
`DEBUG ( default/core ): NfV10 template type : flow`
`DEBUG ( default/core ): NfV10 template ID   : 258`
`DEBUG ( default/core ): -------------------------------------------------------------`
`DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |`
`DEBUG ( default/core ): | 0          | in bytes           [1    ] |      0 |      8 |`
`DEBUG ( default/core ): | 0          | in packets         [2    ] |      8 |      8 |`
`DEBUG ( default/core ): | 0          | tos                [5    ] |     16 |      1 |`
`DEBUG ( default/core ): | 0          | IPv4 src addr      [8    ] |     17 |      4 |`
`DEBUG ( default/core ): | 0          | IPv4 dst addr      [12   ] |     21 |      4 |`
`DEBUG ( default/core ): | 0          | 152                [152  ] |     25 |      8 |`
`DEBUG ( default/core ): | 0          | 153                [153  ] |     33 |      8 |`
`DEBUG ( default/core ): | 0          | input snmp         [10   ] |     41 |      2 |`
`DEBUG ( default/core ): | 0          | output snmp        [14   ] |     43 |      2 |`
`DEBUG ( default/core ): | 0          | ip version         [60   ] |     45 |      1 |`
`DEBUG ( default/core ): | 43823      | 2003               [2003 ] |     46 |  65535 |`
`DEBUG ( default/core ): -------------------------------------------------------------`
`DEBUG ( default/core ): Netflow V9/IPFIX record size : tbd`

`DEBUG ( default/core ): Received NetFlow/IPFIX packet from [x:y] version [10] seqno [857461]`

But nothing is in output (we tried both memory and print plugins):

`  INFO ( default_print/print ): *** Purging cache - START (PID: 22403) ***`
`  INFO ( default_print/print ): *** Purging cache - END (PID: 22403, QN: 0/0, ET: X) ***`

`  pmacct -s`
`  SRC_IP  DST_IP SRC_PORT DST_PORT PROTOCOL PACKETS BYTES`
`  For a total of: 0 entries`

We tried tcpdump+wireshark, incoming packets are decoded and recognized as valid IPFIX flows.

Another set of netflow tools (nfcapd + nfdump) also works (packets are collected and decoded without any warning).

One more thing to mention is that IPFIX datagrams are produced not by Cisco or Juniper boxes, but by VAS Experts DPI (https://vasexpertsdpi.com)

**Comment by paololucente** [comment] 2019-10-02 11:09
Hi @trolyara , thank you for reporting this. Since the template is received and fine and contains all essential info, i am not sure what the issue could be. The most efficient course of action would be if you could send me a sample of these packets (templates + data) via unicast email so that i can reproduce the issue at my end and look into it. Paolo

**Comment by trolyara** [comment] 2019-10-02 12:08
Hi @paololucente ,

Sure, no problem. I've just sent you a unicast email. Thanks!

**Comment by paololucente** [comment] 2019-10-07 13:48
This was a bug related to vlen elements of IPFIX which was already resolved in master code (but still present in 1.7.3).

**Closed** 2019-10-07 13:48 UTC
Labels: bug

**Comment by AnanthGopal** [comment] 2019-10-22 19:41
Hi @paololucente ,

Below i provide the tcp dump data

tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
13:57:47.062420 IP 10.10.110.2.16448 > **10.xxxxxxxx.com.palace-4**: UDP, length 1456

any issue in the above tcpdump because of **10.xxxxxxxx.com.palace-4** is like a domain.

We receive data in tcpdump but nothing is written to memory/print plugin.

pmacct.conf like below

daemonize: true
interface: eth0
logfile: /etc/pmacct/log
aggregate: etype, proto, src_host, src_port, dst_host, dst_port
nfacctd_port: 9995
plugins: print[plugin2]
print_output_file[plugin2]: /etc/pmacct/plugin2.json
print_output[plugin2]: json

we run cmd as nfacctd -f nfacctd.conf -D

We need your help to resolve this issue
