### ISSUE TITLE
is there direction control for pmacctd with libpcap?

### ISSUE THREAD

**Issue by maplewf** [pmacct/pmacct#514] opened 2021-07-12 08:49 UTC
Hi @paololucente,

I'm trying to use pmacctd with libpcap to collect traffic data, I want to classify the traffic of specific interface according to direction.

I saw the directives below in https://github.com/pmacct/pmacct/blob/1.7.5/CONFIG-KEYS:
```
KEY:		[ pcap_direction | uacctd_direction ] [GLOBAL, ONLY_PMACCTD]
VALUES:		[ "in", "out" ]
DESC:		Defines the traffic capturing direction with two possible values, "in" and "out". In
		pmacctd this is used to determine which primitive to populate, whether in_iface or
		out_iface with the pcap_ifindex value. In addition, this allows to tag data basing
		on direction in pre_tag_map. In uacctd the only functionality is the latter of the
		two. 
DEFAULT:	none

KEY:		pcap_ifindex [GLOBAL, PMACCTD_ONLY]
VALUES:		[ "sys", "hash", "map", "none" ]
DESC:		Defines how to source the ifindex of the capturing interface. If "sys" then a
		if_nametoindex() call is triggered to the underlying OS and the result is used; if
		"hash" an hashing algorithm is used against the interface name to generate a unique
		number per interface; if "map" then ifindex definitions are expected as part of a
		pcap_interfaces_map (see below). 
DEFAULT:	none

KEY:		pcap_interfaces_map [GLOBAL, PMACCTD_ONLY, MAP]
DESC:		Allows to listen for traffic data on multiple interfaces (compared to pcap_interface
		where only a single interface can be defined). The map allows to define also ifindex
		and capturing direction on a per-interface basis. The map can be reloaded at runtime
		by sending the daemon a SIGUSR2 signal (ie. "killall -USR2 nfacctd"). Sample map in
                examples/pcap_interfaces.map.example .
DEFAULT:	none
```
I thought that I found the way to archive my goal, but with hours of effort, it didn't work. I wonder if I understand incorrectly or I configure in wrong way. Here is my configuration:

/etc/pmacct/pmacctd-i.conf:
```
daemonize: true
pidfile: /var/run/pmacctd-i.pid
syslog: daemon
promisc: true
pcap_interfaces_map: /etc/pmacct/pcap_iface-i.map
pcap_ifindex: map
pcap_direction: in
aggregate: src_host,src_port,dst_host,dst_port,proto
plugins: print[inbound]
print_refresh_time: 1
print_output_file: /etc/pmacct/pmacctd/inbound/eth1-%Y%m%d-%H%M%S.txt
```
/etc/pmacct/pcap_iface-i.map:
```
ifindex=3	ifname=eth1	direction=in
```
here comes the result, it combines ingress and egress traffic in eth1, which is not what I expect:
```
2.2.2.2                                        1.1.1.2                                        80        37425     tcp         5                     571
1.1.1.2                                        2.2.2.2                                        33569     80        tcp         5                     404
2.2.2.2                                        1.1.1.2                                        80        33569     tcp         5                     571
1.1.1.2                                        2.2.2.2                                        27655     80        tcp         5                     404
2.2.2.2                                        1.1.1.2                                        80        27655     tcp         5                     571
1.1.1.2                                        2.2.2.2                                        16855     80        tcp         5                     404
2.2.2.2                                        1.1.1.2                                        80        16855     tcp         5                     571
1.1.1.2                                        2.2.2.2                                        38649     80        tcp         3                     300
2.2.2.2                                        1.1.1.2                                        80        38649     tcp         2                     112
```

best regards.

**Comment by paololucente** [comment] 2021-07-13 12:50
Hi @maplewf ,

The route you are taking does rely on pcap_setdirection() for pmacctd which, according to its very man page, says `pcap_setdirection() isn't necessarily fully supported on all platforms; some platforms might return an error for all values, and some other platforms might not support PCAP_D_OUT.`. libpcap is a very portable library but it is loosely integrated with any underlying Operating System. 

Would it work for you to determine direction basing on source/destination IP subnet(s) and/or MAC address(es)?

Paolo

**Comment by maplewf** [comment] 2021-07-14 07:06
Hi @paololucente,

The object I want to collect traffic data for is a kind of router, and it can't distinguish the direction according to packet's IP or MAC. May I know what kind of platform can support this feature of pcap? Do you have any list?

My test platform is Debian Jessie which is a bit of old, and version of libpcap and tcpdump is below:
```
libpcap: 1.6.2-2
tcpdump: 4.9.2-1~deb8u1
```
I can easily use `-Q in|out|inout` in tcpdump to classify ingress and egress traffic with above software version, but I don't know if it means that pmacct also can archive this function. If you think there is possibility to archive it by integrating another libpcap, I'm willing to do that as long as you can give me specific version. Thanks in advance.

best regards.

**Comment by paololucente** [comment] 2021-07-14 15:01
Hi @maplewf ,

The fact that tcpdump does honor the `-Q` option is a good sign since that is precisely what pmacct does leverage. I just tested latest pmacct code on a Debian 10.10 and all seems to work fine too (ie. adding `direction=in` to an entry in `pcap_interfaces_map` does get honored).

Can you check in pmacct logs whether you get any warning/error? Also, would it be possible for you to test latest (master) code? Finally, can you test with a super simplified config as follows:

```
pcap_interfaces_map: /etc/pmacct/pcap_iface-i.map
aggregate: src_host,src_port,dst_host,dst_port,proto
```

Where content of `/etc/pmacct/pcap_iface-i.map` is as per your snippet above. And check with `pmacct -s` that you are getting only ingress traffic?

Paolo

**Comment by maplewf** [comment] 2021-07-20 13:56
Hi @paololucente,

Sorry for replying late, I finally get this work, it turns out that the latest release `1.7.6` can work with `pcap_direction` or `direction` in `pcap_interfaces_map`. I'm sorry I didn't specify the version of pmacct(`1.7.2`) I used for testing at first place since I checked history that `pcap_direction` and `direction` in `pcap_interfaces_map` was introduced very early, so I thought that it won't be the reason of problem, it must be underlay dependency like libpcap cause the problem. Anyway, thanks very much for help.

Besides, I also want to take this post to ask another question about exporting flow. I want to export flow generated by pmacct to my own software, there did are many ways provided by pmacct to do it, but so far, none of them is exactly suitable for my requirement. Exporting via `rabbitmq/kafka` is a bit of heavy solution, it requires a lot of resources built around; Export via `Print` to file seems not programmatic and may become a performance bottleneck. 

`Memory` plugin seem to provide socket to hook, but does it allow external process to hook and get flow data? Besides, is it possible to purge cache in memory periodically just like `print` plugin did? 

Or is there other way which is light and more programable in pmacct to export data? Thanks in advance.

best regards.

**Comment by paololucente** [comment] 2021-07-22 13:24
Hi @maplewf ,

I was curious on the why exporting via the `print` plugin does not seem programmatic: i'd agree if you would go with the default formatted output but you may choose, for example, CSV or JSON encodings with `print_output` especially because i read that you like the periodic export of the plugin.

Now, `print` plugin does export to a file. But with `print_trigger_exec` you can have a script of yours to process the closed file to do pretty much what you want. I can't think of a simpler / UNIX-like way of handling things. 

Paolo

**Comment by maplewf** [comment] 2021-07-22 17:42
Hi @paololucente ,

Thanks for reply and patience. I admit that it's straightforward to export data via file by pmacct and then import data from file to my application. But we are talking about inter-process/inter-application communication, exchange data via text file is not modern way, especially for scenarios which require real-time and high performance. 

Besides, I noticed that there is [pull request about ZMQ plugin](https://github.com/pmacct/pmacct/pull/256), you mentioned two reasons to introduce it, which I couldn't agree more, this is exactly what I want to have:
> 1) exporting data to a 3rd party tool without passing through any complex broker-based systems (ie. Kafka, RabbitMQ) 
> 2) as an enabler/code hook to write an actual pmacct plugin in a different language than C/C++

I even tested that patch, but with no luck, it didn't work, I don't know if it's caused by my misunderstanding without docs or it's just because the patch is totally not ready. I have poor knowledge of c/c++ and can't see it through.

Anyway, may I ask what's the progress about this patch? Or is there even any new plan about this zmq plugin?

best regards.

**Comment by paololucente** [comment] 2021-07-23 16:17
Hi @maplewf ,

I can confirm that there is no active effort and hence no progress besides the patch kindly authored and contributed by Will. As i was commenting, relying on ZeroMQ (and more in general TCP) would be the way to go for reliability and also because transferred objects tend to get large (MTU issues). Would you be able to spend some effort on it and contribute it back, i'd be more than happy to give guidance and peer review your code.

Paolo

**Closed** 2021-07-25 17:06 UTC
Labels: question

**Comment by maplewf** [comment] 2021-07-27 12:21
Hi @paololucente,

Sorry for replying late. First of all, I'm very motivated about this task, but to be honest, I have no experience about C programming(most of projects I have evolved are python & golang). Second, I have no idea at all about how to add plugin in pmacct project. But if you still think I'm qualified about it, I'm willing to take this challenge. Here is my email address: maple.feng.wang@hotmail.com, feel free to send your requirement and guide about this plugin to me. Thank for your help.

best regards,
