### ISSUE TITLE
Strange problem with custom primitive

### ISSUE THREAD

**Issue by alexnone** [pmacct/pmacct#186] opened 2018-02-28 13:47 UTC
Hello!
I'm going to use nfaccfd for collection **IPFIX** from my DPI. Now it works OK, I receive a lot of statistic in the flat files. But I've faced with strange problem. I defined a custom primitive to get "**CN HTTPS**" from the DPI.
Here it is:
> name=field2001    field_type=43823:2001    len=vlen    semantics=str

And I receive that field, but with a strange "tail" at the end of the string. For example: "v10.vortex-win.data.microsoft.com.**com**" or "mrilog.mail.ru**lytics.comq**". What's interesting, if I change **semantics** to "**raw**" it seems to be working in a proper way (I can get HEX and convert it to URL by myself). Could you tell me how I can debug this situation?

I use **Centos 7** with **pmacct-1.6.2-1.x86_64.rpm** from Rep.

**Comment by paololucente** [comment] 2018-03-01 11:18
Hi @alexnone,

Thanks for reporting this. I can propose two ways forward for this: 1) you download 1.7.0 (latest stable) or master code from GitHub, compile it yourself and test the problem is still persisting. This is because 1.6.2 is almost one year old; 2) you send me an unicast email with a small trace in pcap format including a few IPFIX data/template packets so that i can perform the exact same checks for you. 

Unless you have a problem with sending the trace, we may prefer to go to straight to option 2 because it saves you time and, shall we determine the issue is persisting in master code, i will need the trace anyway in order to fix it.

Paolo

**Comment by alexnone** [comment] 2018-03-06 06:44
Hi paololucente,

Thank you for your reply!

I've installed a lastest stable version (**pmacct-1.7.0.tar.gz**). Unfortuanelly it did't help me. I still can see the tails in statistic filles. I'm going to send you additional information (pcap+strings with tails) :)

**Comment by paololucente** [comment] 2018-03-07 11:24
Thanks @alexnone for your support and for confirming via unicast email that the fix works. I'm going to close this issue. Paolo

**Closed by paololucente** 2018-03-07 11:24 UTC
Labels: bug
