### ISSUE TITLE
Tags are mssing

### ISSUE THREAD

**Issue by jean-christophe-manciot** [pmacct/pmacct#72] opened 2016-11-24 13:33 UTC
```
git describe --tags
fatal: No names found, cannot describe anything.
```
They would help us know which commit corresponds to which version release number in the master branch.
For instance: v1.6.1
Otherwise, we have no way of discovering that information when a stable version is ready, since even the comments do not detail that information.
Tags are much easier to parse though.

**Comment by paololucente** [comment] 2016-11-27 00:59
Dear Jean-Christophe,

Thanks for your report; I have this item on my todo list. This issue is duplicate of issue #36 that is still open. Hope you don't mind if i close this up.

Regards,
Paolo

**Closed by paololucente** 2016-11-27 00:59 UTC
Labels: duplicate
