### ISSUE TITLE
Does uacctd  support to export if_name field for Netflow v9

### ISSUE THREAD

**Issue by maplewf** [pmacct/pmacct#299] opened 2019-07-17 18:50 UTC
Hello,

I'm new for using pmacct, recently I used uacctd with nfprobe plugin to export traffic statistics of my Linux host via Netflow V9, but one thing bother me a lot: only `ifindex` is exported for each flow, technically, it's `input_snmp` and `output_snmp` in netflow, `ifindex` is not permanent since it might be changed once while especially host was rebooted.

I know `if_name` is field supported by netflow V9, but I can't find the way to add this field in uacct configuration. So I wonder if it's not supported by pmacct/uacct or there is another way to do it. Really appreciate if anyone can help, thanks in advance.

best regards.

**Comment by paololucente** [comment] 2019-07-18 12:34
Hi @maplewf ,

Interface names are not supported when exporting NetFlow/IPFIX. For libpcap collection, pmacctd, there is a way to achieve this: listening on an interface, ie. eth0, and then defining an ifindex via pcap_interfaces_map - so you would be in total control; there is not such mechanism for uacctd however you could issue tags (or labels) basing on source and destination MAC addresses, see https://github.com/pmacct/pmacct/blob/1.7.3/QUICKSTART#L1243-L1295 (only constrain is that then you have to collect traffic with pmacct, nfacctd daemon, since tags and labels are non-standard fields). I reckon the solution may look a bit convoluted.

Paolo

**Comment by maplewf** [comment] 2019-07-18 12:56
Hi Paolo,

Thanks for your help. Unfortunately, in current solution, uacctd + netflow seems necessary for us(the cost is too much if we switch to totally different solution). 

The thing really bothering us is that uncertainty of ifindex in Linux, so I came up with a rough idea according to you suggestion. 

There will be certain mapping relationship between interface name and index maintained by local process. `tag` will be assigned with this mapping index for flow of certain interface. then `nfprobe_ifindex` will be set to tag value in uaactd configuration. what do you think?

mac address has its limitation since some type of interface has no mac like tunnel interface, that's why i think to use local process to fix the mapping of index and name

best regards.

**Comment by maplewf** [comment] 2019-07-18 17:29
Hello Paolo,

I just tried to add tag in pretag.map like following:

`set_tag=100 in=2` , in this format, there is no flow matched, I found only `set_tag=2 in=2` or `id=2 in=2` can match flow, tag/id must be same as interface index

then I tried with set second tag without touching first tag like following:
`set_tag=2 in=2 jeq=eth0`
`set_tag2=100 label=eth0`
it can match flow, but tag2 will never be set

I checked https://github.com/pmacct/pmacct/blob/master/examples/pretag.map.example, uacctd seems not be mentioned in there, does it mean uacctd doesn't support tag?

or there is something wrong in my configuration?

here is my uacctd configuration:
```
daemonize: true
promisc:   false
pidfile:   /var/run/uacctd-i.pid
imt_path:  /tmp/uacctd-i.pipe
imt_mem_pools_number: 169
uacctd_group: 2
uacctd_nl_size: 2097152
snaplen: 4096
timestamps_secs: true
refresh_maps: true
pre_tag_map: /etc/pmacct/int_map-i
aggregate: tag,src_mac,dst_mac,vlan,src_host,dst_host,src_port,dst_port,proto,tos,flows
plugin_pipe_size: 10485760
plugin_buffer_size: 10240
syslog: daemon
plugins: memory[memory-ingress],nfprobe[192.168.18.33-2055-nfprobe-ingress]
nfprobe_receiver[192.168.18.33-2055-nfprobe-ingress]: 192.168.18.33:2055
nfprobe_version[192.168.18.33-2055-nfprobe-ingress]: 9
nfprobe_direction[192.168.18.33-2055-nfprobe-ingress]: in
nfprobe_ifindex[192.168.18.33-2055-nfprobe-ingress]: tag
```
int_map-i:
```
set_tag=100 in=2
```

**Comment by paololucente** [comment] 2019-07-20 13:26
Hi @maplewf ,

One step back in order to validate what is going on with the pre_tag_map: if you add 'in_iface' to the 'aggregate' line, do you see in the memory plugin any packets coming from such interface? If not, that is the issue and you could actually review which interface id packets are coming from; if yes, then we have to dig deeper. To briefly confirm that, yes, tagging on interfaces is supported also for uacctd.

Paolo

**Comment by maplewf** [comment] 2019-07-20 18:52
Hi Paolo,

Thanks for help, I did see the tag in the memory plugin as below:

```
/usr/bin/pmacct -a -p /tmp/uacctd-i.pipe -s -T packets
TAG         TAG2        CLASS             IN_IFACE    OUT_IFACE   SRC_MAC            DST_MAC            VLAN   COS ETYPE  SRC_AS      DST_AS      COMMS                    SRC_COMMS                AS_PATH                  SRC_AS_PATH              PREF     SRC_PREF MED     SRC_MED SYM  PEER_SRC_AS PEER_DST_AS PEER_SRC_IP                                    PEER_DST_IP                                    SRC_IP                                         DST_IP                                         SRC_MASK  DST_MASK  SRC_PORT  DST_PORT  TCP_FLAGS  PROTOCOL    TOS    SH_COUNTRY  DH_COUNTRY  SAMPLING_RATE SAMPLING_DIRECTION POST_NAT_SRC_IP                                POST_NAT_DST_IP                                POST_NAT_SRC_PORT  POST_NAT_DST_PORT  NAT_EVENT MPLS_LABEL_TOP  MPLS_LABEL_BOTTOM  MPLS_STACK_DEPTH  TUNNEL_SRC_IP                                  TUNNEL_DST_IP                                  TUNNEL_PROTOCOL  TUNNEL_TOS  TIMESTAMP_START                TIMESTAMP_END                  TIMESTAMP_ARRIVAL              EXPORT_PROTO_SEQNO  EXPORT_PROTO_VERSION  EXPORT_PROTO_SYSID  PACKETS               FLOWS                 BYTES
100         0           unknown           0           0 
```

But with configuration above, I still can't see that interface index in netflow(`output_snmp` and `input_snmp`) turn to be the value of tag.

I noticed that there is statement in https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L2127:
`This definition will be also always overridden whenever the ifIndex can be determined dynamically (ie. via NFLOG framework)`

I am using NFLOG with uacctd, does it means that I never be able to use nfprobe_ifindex with tag value to overwrite orignal ifindex? 

best regards

**Comment by paololucente** [comment] 2019-07-21 01:48
Hi @maplewf , 

Let's proceed step by step (mostly because i don't have a setup handy to reproduce NFLOG myself; if it's a possibility to access remotely your system via ssh, i'd be more than willing to save you the back and forth); let's take NetFlow out of the picture; in the memory plugin instantiated in uacctd, can you see any non-zero input and/or output interface index? If that is already not the case then we have a problem (ie. collecting NFLOG from the wrong chain?). What system by the way are you running all of this - distribution and version? 

Paolo

**Comment by maplewf** [comment] 2019-07-21 12:32
Hi Paolo,

Thanks for your kind help. Firstly, I'm sorry I have no public system for your access remotely. But I promise that I will describe the situation there as much as possible:

For now, the pre_tag_map is like below:
```
set_tag=100     in=2
``` 
And uacctd.conf is like below:
```
daemonize: true
promisc:   false
pidfile:   /var/run/uacctd-i.pid
imt_path:  /tmp/uacctd-i.pipe
imt_mem_pools_number: 169
uacctd_group: 2
uacctd_nl_size: 2097152
snaplen: 4096
timestamps_secs: true
refresh_maps: true
pre_tag_map: /etc/pmacct/int_map-i
aggregate: tag,in_iface,src_mac,dst_mac,vlan,src_host,dst_host,src_port,dst_port,proto,tos,flows
plugin_pipe_size: 10485760
plugin_buffer_size: 10240
syslog: daemon
plugins: memory[memory-ingress],nfprobe[192.168.18.33-2055-nfprobe-ingress]
nfprobe_receiver[192.168.18.33-2055-nfprobe-ingress]: 192.168.18.33:2055
nfprobe_version[192.168.18.33-2055-nfprobe-ingress]: 9
nfprobe_direction[192.168.18.33-2055-nfprobe-ingress]: in
nfprobe_ifindex[192.168.18.33-2055-nfprobe-ingress]: tag
```
And this is the content of pipe file:
```
TAG         TAG2        CLASS             IN_IFACE    OUT_IFACE   SRC_MAC            DST_MAC            VLAN   COS ETYPE  SRC_AS      DST_AS      COMMS                    SRC_COMMS                AS_PATH                  SRC_AS_PATH              PREF     SRC_PREF MED     SRC_MED SYM  PEER_SRC_AS PEER_DST_AS PEER_SRC_IP                                    PEER_DST_IP                                    SRC_IP                                         DST_IP                                         SRC_MASK  DST_MASK  SRC_PORT  DST_PORT  TCP_FLAGS  PROTOCOL    TOS    SH_COUNTRY  DH_COUNTRY  SAMPLING_RATE SAMPLING_DIRECTION POST_NAT_SRC_IP                                POST_NAT_DST_IP                                POST_NAT_SRC_PORT  POST_NAT_DST_PORT  NAT_EVENT MPLS_LABEL_TOP  MPLS_LABEL_BOTTOM  MPLS_STACK_DEPTH  TUNNEL_SRC_IP                                  TUNNEL_DST_IP                                  TUNNEL_PROTOCOL  TUNNEL_TOS  TIMESTAMP_START                TIMESTAMP_END                  TIMESTAMP_ARRIVAL              EXPORT_PROTO_SEQNO  EXPORT_PROTO_VERSION  EXPORT_PROTO_SYSID  PACKETS               FLOWS                 BYTES
100         0           unknown           2           0           
100         0           unknown           2           0           
100         0           unknown           2           0          
100         0           unknown           2           0          
100         0           unknown           2           0          

For a total of: 5 entries
``` 
> There are some sensitive information like ip and mac address is removed from printout above for privacy, but you can see that tag and ifindex works as expect.

And  data source of NFLOG is collected by iptable rule below:
```
iptables -t raw -A PREROUTING -i eth0 -j NFLOG --nflog-group 2 --nflog-range 64 --nflog-threshold 10
```
> Note: ifindex of eth0 is `2`

It's pretty early enough for ingress traffic collection. I think it's standard setup for NFLOG data collection. I can get netflow reported in elasticsearch(we export netflow to elasticsearch via logstash), everything works fine except I can't use tag value to overwrite the original ifindex by using `nfprobe_ifindex` when it's exported via netflow. You can see what I got in elasticsearch:
![image](https://user-images.githubusercontent.com/18524415/61591175-ff4bb680-abf5-11e9-86b7-c1ef4592aa17.png)

The system I'm monitoring for is `debian jessie` and the version of uacctd is `1.7.2-git (20181018-00+c3)`, hope these information is helpful for troubeshooting this problem.

Really appreciate your kind help.

best regards.

**Comment by paololucente** [comment] 2019-07-24 19:19
Hi @maplewf , 

Thank you for the extra insight. The relevant section of code in 'nfprobe' to determine what will be the input interface in a NetFlow/IPFIX flow is here: https://github.com/pmacct/pmacct/blob/master/src/nfprobe_plugin/nfprobe_plugin.c#L326-L343 . Specifically line 326 is what does the 'override' that you spotted in documentation. May i ask you to: 1) comment out / delete line 326 and 2) change the "else if" construct in "if" on line 327 then 3) recompile the binary? Does this change work for you to see the input interface changed to '100'? If so i can code a config directive to optionally change the desired behaviour to this one.

Paolo

**Comment by maplewf** [comment] 2019-07-30 05:27
Hi Paolo,

Thanks very much for your suggestion, and I already recompiled source according to your instruction, it actually works, tag value can be reflected in netflow field `input_snmp` and `output_snmp` as below:
![image](https://user-images.githubusercontent.com/18524415/62102708-853dc080-b2cc-11e9-9304-435eff69d53e.png) 

But somehow, my logstash wouldn't accept the netflow data from recompiled pmacct daemon, I wonder if there is something wrong in my procedure of compilation. But anyway, I will try to figure it out later, thanks for your great support.

best regards.

**Comment by paololucente** [comment] 2019-07-30 18:32
Hi @maplewf ,

Wonderful. Thanks for confirming it works like that - i will add a config knob so that the override can be made possible (that is, without having to recompile the code like you had to do).

Wrt, why "logstash wouldn't accept the netflow data from recompiled pmacct daemon": did it accept data just fine before the code change? I suspect not otherwise i'd be very puzzled. I am not sure since i don't know the receiving software but try to remove from the 'aggregate' line the 'tag' keyword; try also perhaps to play with the export version (set it to 10, IPFIX, instead of 9).

Paolo

**Comment by paololucente** [comment] 2019-07-31 18:49
Hi @maplewf , to say i've committed the code. Adding 'nfprobe_ifindex_override: true' to your config should now make the trick. Let me know if this appears to work for you. Paolo

**Closed** 2019-08-06 13:10 UTC
Labels: enhancement
