### ISSUE TITLE
Not all primitives work and some are mapped to wrong type in JSON.

### ISSUE THREAD

**Issue by hyberdk** [pmacct/pmacct#505] opened 2021-05-21 09:29 UTC
**Description**
I have extended the netflow fields that I need to collect from my Cisco routers and firewalls. Some of the fields are working and some are not. I cannot really make sense of it.

here is my configurations:

```
root@flowapp01:/opt/nfacct# cat primitives.lst 
name=direction          field_type=61   len=1   semantics=u_int
name=appid              field_type=95   len=4   semantics=hex
name=dscp               field_type=195  len=1   semantics=u_int
name=postNATSrcIP       field_type=225  len=4   semantics=ip
name=postNATDstIP       field_type=226  len=4   semantics=ip
name=postNATSrcPort     field_type=227  len=2   semantics=u_int
name=postNATDstPort     field_type=228  len=2   semantics=u_int
name=initiatorOctets    field_type=231  len=8   semantics=u_int
name=responderOctets    field_type=232  len=8   semantics=u_int
name=firewallEvent      field_type=233  len=1   semantics=u_int
name=biflowDirection    field_type=239  len=2   semantics=u_int
name=transactionid      field_type=280  len=8   semantics=u_int
name=firewallEventExt   field_type=33002  len=2 semantics=u_int
name=ingressACL         field_type=33000  len=12    semantics=hex
name=egressACL          field_type=33001  len=12    semantics=hex
name=aaa_username       field_type=40000  len=65    semantics=str
root@flowapp01:/opt/nfacct# 

```

```
root@flowapp01:/opt/nfacct# cat nfacctd.conf
!
!
! AUTOGENERATED FILE @ Thu May 20 13:35:57 UTC 2021 - PLEASE EDIT TEMPLATE INSTEAD
!
! General configs
!
debug: false
daemonize: false
!logfile: nfacct.log

!additional fields for netflow.
aggregate_primitives: /opt/nfacct/primitives.lst

!pretag to patch bi-directional flows and put that into another kafka topic
pre_tag_map: /opt/nfacct/pretag.map
!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: 3011
! nfacctd_time_secs: true
! nfacctd_time_new: true


plugins: kafka[uni-flow], kafka[bi-flow]
!
pre_tag_filter[uni-flow]: 100
aggregate[uni-flow]: tos,dscp,direction,appid,proto,src_host,dst_host,src_port,dst_port,in_iface,out_iface,peer_src_ip,biflowdirection
kafka_output[uni-flow]: json
kafka_topic[uni-flow]: netflow-collector
kafka_refresh_time[uni-flow]: 60
kafka_history[uni-flow]: 1m
kafka_history_roundoff[uni-flow]: m
kafka_broker_host[uni-flow]: flowapp01
kafka_broker_port[uni-flow]: 9092
kafka_cache_entries[uni-flow]: 160000
! do not translate IP protocols into names, but keep ID
kafka_num_protos[uni-flow]: true

pre_tag_filter[bi-flow]: 200
aggregate[bi-flow]: proto,src_host,dst_host,src_port,dst_port,in_iface,out_iface,peer_src_ip,initiatoroctets,responderoctets,firewallevent,firewalleventext,postnatsrcip,postnatdstip,postnatsrcport,postnatdstport,ingressacl,egressacl,aaa_username
kafka_output[bi-flow]: json
kafka_topic[bi-flow]: netflow-collector-biflow
kafka_refresh_time[bi-flow]: 60
kafka_history[bi-flow]: 1m
kafka_history_roundoff[bi-flow]: m
kafka_broker_host[bi-flow]: flowapp01
kafka_broker_port[bi-flow]: 9092
kafka_cache_entries[bi-flow]: 160000
! do not translate IP protocols into names, but keep ID
kafka_num_protos[bi-flow]: true
```

```
root@flowapp01:/opt/nfacct# cat pretag.map 
set_tag=200 is_bi_flow=true
set_tag=200 sample_type=event
set_tag=100 is_bi_flow=false
set_tag=100 sample_type=flow

```

The ones that are not working for me are the following ones:

```
name=biflowDirection    field_type=239  len=2   semantics=u_int
name=firewallEventExt   field_type=33002  len=2 semantics=u_int
name=ingressACL         field_type=33000  len=12    semantics=hex
name=egressACL          field_type=33001  len=12    semantics=hex
name=aaa_username       field_type=40000  len=65    semantics=str
```

at first I just thought it was the high number of the field id, but the biflowDirection is also not working..

here is a sample JSON from the kafka topic with the biflowDirection being "0"

`{"event_type": "purge", "peer_ip_src": "10.10.5.203", "iface_in": 73, "iface_out": 0, "ip_src": "10.12.33.239", "ip_dst": "10.8.8.11", "port_src": 53231, "port_dst": 2055, "ip_proto": "17", "tos": 64, "dscp": "0", "direction": "0", "appid": "0", "biflowdirection": "0", "stamp_inserted": "2021-05-21 09:19:00", "stamp_updated": "2021-05-21 09:20:15", "packets": 0, "bytes": 17966, "writer_id": "uni-flow/9510"}`

all the biflowDirection are always "0", regardless of what is sent. here is a screenshot from wireshark (not the same sample as above just a random one)

![image](https://user-images.githubusercontent.com/3530739/119115202-332cd880-ba27-11eb-80bb-feadbd5d888d.png)

Any ideas?

Also, it seems like "custom" fields in the primitives.lst file are sometime sent as "string" in the JSON file. See "direction", ip_proto, dscp but not always. tos seems fine..

**Version**

```
root@flowapp01:/opt/nfacct# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.7-git [20210516-0 (676f4e97)]

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.4
libpcap version 1.9.1 (with TPACKET_V3)
rdkafka 1.2.1
jansson 2.12

Plugins:
memory
print
nfprobe
sfprobe
tee
kafka

System:
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64

Compiler:
gcc 9.3.0

```

Esben

**Comment by paololucente** [comment] 2021-05-21 19:24
Hi Esben ( @hyberdk ),

You may notice how on this line there is a value of 8 defined: https://github.com/pmacct/pmacct/blob/master/src/cfg.h#L31 . I will try to reproduce your scenario during the weekend, meanwhile would it be possible for you to do a quick test: change that 8 in, say, 16 recompile and see if all goes fine and dandy?

Paolo

**Comment by hyberdk** [comment] 2021-05-22 19:39
Hi Paolo (@paololucente),

I tried with this code https://github.com/hyberdk/pmacct/commit/a30f7c9d7e472a0da7b3c4b38d803ef67f9a8832, but unfortunately it did not work.

here is the version: 

```
root@flowapp01:/opt/nfacct# nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.7-git [20210522-0 (a30f7c9d)]

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.4
libpcap version 1.9.1 (with TPACKET_V3)
rdkafka 1.2.1
jansson 2.12

Plugins:
memory
print
nfprobe
sfprobe
tee
kafka

System:
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64

Compiler:
gcc 9.3.0
```

here is a sample output in the kafka topic:

```
{
  "event_type": "purge",
  "peer_ip_src": "10.12.33.239",
  "iface_in": 20,
  "iface_out": 1,
  "ip_src": "192.168.0.2",
  "ip_dst": "185.125.227.110",
  "port_src": 5908,
  "port_dst": 8080,
  "ip_proto": "6",
  "tos": 0,
  "dscp": "0",
  "direction": "1",
  "appid": "d000309",
  "biflowdirection": "0",
  "stamp_inserted": "2021-05-22 19:24:00",
  "stamp_updated": "2021-05-22 19:25:09",
  "packets": 0,
  "bytes": 777,
  "writer_id": "uni-flow/185"
}
```

biFlowdirection is still "0" ;-(

here is the same flow but captured in a tcpdump

![image](https://user-images.githubusercontent.com/3530739/119238920-df64e100-bb45-11eb-9520-2c8c685996ae.png)

Esben

**Comment by paololucente** [comment] 2021-05-24 21:34
Hi Esben,

Ack about the code change. The specific bi-flow direction may be different: you defined it as `name=biflowDirection    field_type=239  len=2   semantics=u_int` but the field has length 1: if you replace `len=2` with `len=1`, it should decode properly.

Paolo

**Comment by hyberdk** [comment] 2021-05-25 06:50
Hi Paolo (@paololucente)

> but the field has length 1: if you replace `len=2` with `len=1`

awww maaaaan.. what a silly mistake.. it works now.. awesome..

however I do have issues with some of the other fields, these three

```
name=firewallEventExt   field_type=33002  len=2 semantics=u_int
name=ingressACL         field_type=33000  len=12    semantics=hex
name=egressACL          field_type=33001  len=12    semantics=hex
```

I double checked, len seems fine ;-)

![image](https://user-images.githubusercontent.com/3530739/119451168-3bda2300-bd35-11eb-81e0-d9d279cc9504.png)

The [documentation](https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html#pgfId-1349333) from Cisco also confirms it..

I did also have issues with the 

`name=aaa_username       field_type=40000  len=20    semantics=str`

but once I switched it to len=20 instead of len=65, then it worked. Acording to the Cisco documentation (and templates exported), it can have both length.. Not sure if nfacctd, can handle if I did something like:

```
name=aaa_username       field_type=40000  len=20    semantics=str
name=aaa_username       field_type=40000  len=65    semantics=str
```

Finally, why is there a limit of 8 primitives? Is it some sort of a performance thing?

Thanks for your help Paolo!

Esben

**Comment by paololucente** [comment] 2021-05-25 13:45
Hi Esben,

Cool that two of the primitives now work. Can you send me a pcap trace via unicast email that includes the scenario where the other three are not working? I did look in the capture you sent me previously for this issue but that template id 265 is not there. 

You can't have two primitives with the same name, ie. `aaa_username`, but you can name them differently and include both in your aggregate: custom primitives do not utilize space unless they are used and only one of the two would be used at any time anyway; drawback: you may have two fields to check in the output JSON and mux them in the same field in the DB. Honestly this is all happening simply because the device is exporting NetFlow v9 (which can only export fixed-length fields), this would have been resolved nicely by IPFIX and variable-length fields.

`Finally, why is there a limit of 8 primitives? Is it some sort of a performance thing?`: can you confirm moving this value back and forth 8 and 16 does make a difference for you? In any case, yeah, it was meant as a security valve along with the usual thinking "who will ever need to define heaps of custom primitives?" :-D No big penalties in raising this value to 16, 32, 64, etc. Just, before doing that, i'd like to be sure it's making a difference for you, hence the question.

Paolo

**Comment by hyberdk** [comment] 2021-05-25 19:33
> Can you send me a pcap trace via unicast email that includes the scenario where the other three are not working?

will do..

> You can't have two primitives with the same name, ie. aaa_username, but you can name them differently and include both in your aggregate

hmm.. both these primitives are used in my biflow. Its the same ASA box that are sending both a 20byte and a 65byte version of `aaa_username`. Template 270 is 65bytes and template 271 is 20bytes. So can I just name them `aaa_username20` and `aaa_username65`, but still keep the same field ID 40000 although its in the same collector.

> can you confirm moving this value back and forth 8 and 16 does make a difference for you?

I tried to lower it to 8 again, it seems to be working still (at least for my uni-flow). But as far as I understand it, if a collector goes beyond 8 (active utilized), it will not work? 

Im missing a list of aggregate->field number, so I can reference the built-in version. The only thing I have found is: https://github.com/pmacct/pmacct/blob/a7039fa66d95ca56053b81e7bf90adfbb00a4086/CONFIG-KEYS#L49-L64 but there are no field IDs. I think some of them overlaps with my primitives.

like these:
- fw_event -> firewallEvent (233)
- post_nat_src_host -> postNATSrcIP (225)
- post_nat_dst_host -> postNATDstIP (226)
- post_nat_src_port -> postNATSrcPort (227)
- post_nat_dst_port -> postNATDstPort (228)

Anyways performance wise eg. number of flows that it can collect. I didnt really test it nor looked at the CPU util.. I have 6 containers running, I tested it waaay back when and landed around 20K flow/sec per container and I only push about 60K flows/sec into my system.

I could try and test it with a single container and see if there are any difference in how many flows it can handle with 8 vs. 16. I should only take me an hour or two to clone to flows into a new container and have it push all it can into a new table.

**Comment by paololucente** [comment] 2021-06-04 15:55
Hi Esben ( @hyberdk ),

Picking up on this thread again. 

- I did owe you an answer wrt firewallEventExt, ingressACL and egressACL not being printed out. For the ACLs it's simple: semantics is set to `hex` (hex representation of an integer) instead of `raw` (hex dump of some binary data). This is documented but i full get where the confusion comes from. Whereas firewallEventExt does just print out fine for me.

- Your solution of having two primitives, ie. aaa_username20 and aaa_username65, pointing to the same field type but with different lengths would work just fine - yes! 

- And also, yes!, all the fields that you mention (firewallEvent, postNATSrcIP, postNATDstIP, postNATSrcPort, postNATDstPort) are supported natively so you can avoid re-defining them as custom primitives. I take as an Action Item for me to improve documentation: you are right, there is nowhere documented which primitive in pmacct does map to which field type in NetFlow/IPFIX).

Paolo

**Closed** 2021-07-10 16:37 UTC
Labels: mia
