### ISSUE TITLE
SFLFLOW_EX_TAG, CLASS Documentation

### ISSUE THREAD

**Issue by manitonetworks** [pmacct/pmacct#71] opened 2016-11-24 05:45 UTC
I'm in the process of finalizing code for an sFlow collector in the Manito Networks Flow Analyzer project and I'm seeing some records that I can't figure out how to parse - Enterprise 8800, Format 2. These are coming from VyOS and Ubiquiti devices, and there's nothing in their documentation about it. In sFlow code comments it's mentioned that 8800, 2 comes from pmacct and that's it. The folks on the sFlow mailing list directed me to you all. I've dug through the pmacct code and found SFLFLOW_EX_TAG, SFLFLOW_EX_CLASS, etc but can't find a structure definition that shows how to parse it.

I've unpacked an 8800, 2 record and gotten "4", but then the Python XDR unpacker errors out indicating that unpacked data still remains, but I have no way of knowing what it is. I assume that "4" corresponds with a pre-defined value somewhere.

Can you point me to the structure documentation for records sent by enterprise 8800? If the documentation hasn't been done yet I'd be happy to do it. Thanks!

My previous conversation with the sFlow folks: https://groups.google.com/forum/#!topic/sflow/nyT4KcnO6DM

**Comment by paololucente** [comment] 2016-11-27 01:08
Dear Tyler,

Thanks for raising the point. I'm afraid to confirm this is a case of squatting enterprise number #8800 while pmacct has got assigned by IANA enterprise number #43874 - the rationale behind is that the squat happened well before being assigned the own enterprise number and, as in many non-happy ending stories, it never got changed. This would be a first fix for this issue.

From your description there appears to be a second problem, related to decoding the actual value. Any chance you can send me by unicast email a brief capture with one or a handful sFlow datagrams that you are trying to decode? I'd inspect them manually and also pass them under sfacctd to see whether they are decoded fine there.

Regards,
Paolo

**Comment by manitonetworks** [comment] 2016-11-27 20:18
Paolo,

I'm not sure where to find your email so I just tossed a PCAP up in my sFlow branch: https://gitlab.com/thart/flowanalyzer/blob/sFlow/Python/sflow/Ubiquiti%20sFlow%20Dump.pcap

There's brief sFlow captures from two Ubiquiti devices that include 8800,2 records. Thanks for working this issue, I appreciate it.

-Tyler

**Comment by manitonetworks** [comment] 2016-12-06 03:34
Were you able to get what you needed from that PCAP file?

**Comment by paololucente** [comment] 2016-12-06 23:34
Dear Tyler,

Apologies for not getting back to you earlier. I could not make much use of the pcap because injecting it into Wireshark just tells that it's all malformed packets (without pointing to the specific reason). But the good news is i could reproduce the issue and i'm currently looking into it.  

One question i have is: are tags configurable on Ubiquiti or they come as part of a default/canned kind of config? While it's good to get this issue solved, knowing tags are configurable would remove some pressure.

**Comment by manitonetworks** [comment] 2016-12-07 04:28
Paolo,

Sorry the PCAP wasn't more help to you. There aren't any configurable options that I've been able to find for sFlow on Ubiquiti EdgeOS or in Vyatta / VyOS. The only configurable options for sFlow are as follows (set on one of my lab routers):
```
vyos@vyos# show system flow-accounting sflow
    agent-address 192.168.56.2
    sampling-rate 1
    server 192.168.56.1 {
        port 6343
    }
```

**Comment by paololucente** [comment] 2016-12-07 16:35
Hi Tyler,

As you can see above i just fixed another issue i found wrt tags & sFlow. This is something extra. I'm a bit puzzled because with sflowtool, which is my tool of reference when it comes to decoding sFlow (since it's coded by InMon), i can decode no problem both old output (the one squatting enterprise #8800) and the new one (with the correct enteprise number and field size), see below (interesting part marked with "<--"):

sampleType_tag 0:1
sampleType FLOWSAMPLE
sampleSequenceNo 437
sourceId 0:1
meanSkipCount 1
samplePool 437
dropEvents 0
inputPort 1
outputPort 1073741823
flowBlock_tag 0:1001
extendedType SWITCH
in_vlan 0
in_priority 0
out_vlan 0
out_priority 0
flowBlock_tag 43874:2  <--
skipping unknown flow_sample_element: 43874:2 len=16  <--
flowBlock_tag 0:1
flowSampleType HEADER
headerProtocol 1
sampledPacketSize 278
strippedBytes 4
headerLen 128
[ .. ]

Wireshark unfortunately reports packets as malformed but i suspect this is a bug of the dissector for two reasons: 1)  sflowtool decodes the packet just OK and 2) double checking bytes on the wire all looks good (sFlow header tag and size and field values). Do you want to give a try yourself decoding sFlow output of the Ubiquiti with InMon sflowtool?

If there is some problem with that, i see that there is a VyOS-pmacct repo here on GitHub: https://github.com/vyos/pmacct . Maybe you can open a bug with them and/or get in touch with the maintainers?

**Closed** 2016-12-08 17:25 UTC
Labels: bug

**Comment by manitonetworks** [comment] 2016-12-09 01:59
Can you point me to the documentation of the structure 43874:2 ?

Now that the new Enterprise number is in use I'd like to add a module to my code for unpacking that structure.

**Comment by paololucente** [comment] 2016-12-09 14:19
On one hand i'm sorry to say that there is no documentation; on the other, encoding is pretty simple: 

typedef struct _SFLExtended_tag {
  pm_id_t tag;
  pm_id_t tag2;
} SFLExtended_tag;

Where pm_id_t is a typedef for u_int64_t.

**Comment by manitonetworks** [comment] 2016-12-10 00:26
That's what I've been looking for! Thanks very much, I'll add that parser to my code, as well as documentation.

**Comment by paololucente** [comment] 2016-12-18 22:16
FYI, a case was opened by @andamasov to update the pmacct package in VyOS:

https://phabricator.vyos.net/T221
