### ISSUE TITLE
Segmentation fault in sfacctd when using pretag maps

### ISSUE THREAD

**Issue by tarrychk** [pmacct/pmacct#370] opened 2020-02-14 13:27 UTC
sfacctd 1.7.4p1 is segfaulting when I run it with pretag map configuration.
sfacctd 1.7.4 with same configuration was working but showed the memory leak that was fixed with 1.7.4p1 and the label inserted had trailing characters.
1.7.3 is working fine.

Content of pre_tag_map file:
```
set_label=123 ip=0.0.0.0/0
```

**Version**
INFO ( default/core ): sFlow Accounting Daemon, sfacctd 1.7.4-git (20191126-01+c6)
INFO ( default/core ):  '--enable-64bit' '--enable-kafka' '--enable-jansson' '--enable-nflog' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

**Operating system**
Alpine 3.11

**Backtrace**
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa090f1a5b9 in free () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 40)]
(gdb) bt
#0  0x00007fa090f1a5b9 in free () from /lib/ld-musl-x86_64.so.1
#1  0x0000557a118ff517 in pretag_free_label (label=label@entry=0x557a27063f80) at pretag.c:801
#2  0x0000557a118ff6d6 in pretag_entry_process (e=0x7fa08f263020, pptrs=pptrs@entry=0x7ffd89373330, tag=tag@entry=0x7ffd893733c0, tag2=tag2@entry=0x7ffd893733d0) at pretag.c:882
#3  0x0000557a118c10f7 in SF_find_id (t=0x557a127e8588, pptrs=0x7ffd89373330, tag=0x7ffd893733c0, tag2=0x7ffd893733d0) at sfacctd.c:2101
#4  0x0000557a118d065b in exec_plugins (pptrs=0x7ffd89373330, req=0x7ffd89372ca0) at plugin_hooks.c:401
#5  0x0000557a118c4013 in finalizeSample (sample=<optimized out>, pptrsv=<optimized out>, req=<optimized out>) at sfacctd.c:1729
#6  0x0000557a118c79bf in readv5FlowSample (sample=<optimized out>, expanded=<optimized out>, pptrsv=0x7ffd893730e0, req=0x7107fc324c40cfd, finalize=1) at sflow.c:1182
#7  0x0000557a118c225b in process_SFv5_packet (spp=spp@entry=0x7ffd89383010, pptrsv=pptrsv@entry=0x7ffd893730e0, req=req@entry=0x7ffd89372ca0, agent=agent@entry=0x7ffd89372d90) at sfacctd.c:1483
#8  0x0000557a118c0239 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at sfacctd.c:1337
```

Issue seems to be that the label is not properly initialized. val should be 0:
```
(gdb) frame 1
#1  0x0000557a118ff517 in pretag_free_label (label=label@entry=0x557a27063f80) at pretag.c:801
801     pretag.c: No such file or directory.
(gdb) p *label
$1 = {len = 3, val = 0x557a2b9247c0 "\220J\222+zU"}
```
The problematic label structure gets passed down from the calling functions:
```
[frame 4]
(gdb) p *(p->cfg.ptm->e)
$10 = {id = 0, id2 = 0, label = {len = 3, val = 0x557a2b9247c0 "\220J\222+zU"}, [...]
```

**Comment by paololucente** [comment] 2020-02-14 17:42
Hey Ed ( @tarrychk ),

Thanks very much for reporting this. Can you please try master code or apply this patch ( https://github.com/pmacct/pmacct/commit/4e648cc96aae99ee5f4b1c9e135a1afa73b864b3 ) to 1.7.4 that you are running? A similar issue was by coincidence reported yesterday and fixed and i believe the root cause is the same as the issue described here. Please let me know.

Paolo

**Comment by tarrychk** [comment] 2020-02-17 10:14
pmacct 1.7.4p1 with the relevant portion of 4e648cc applied does not crash anymore. I'll update later about the state of the memory leak.

**Comment by tarrychk** [comment] 2020-02-18 08:26
So far memory consumption of 1.7.4p1 looks fine, too.

**Comment by paololucente** [comment] 2020-02-18 13:37
Wonderful, thanks for confirming. I will then close this issue. Paolo

**Closed by paololucente** 2020-02-18 13:37 UTC
Labels: bug
